import test from 'node:test';
import assert from 'node:assert/strict';
import {database} from '../server/db.js';
import worker,{createAdmin,resetPassword} from '../server/app.js';

test('complete account, authorization, catalog, progress and administration lifecycle',async t=>{
 const DB=database(),env={DB},origin='https://arrivo.example.test';
 const call=async(path,{method='GET',body,cookie,csrf=true}={})=>{const headers=new Headers({'Content-Type':'application/json','x-arrivo-client-ip':'127.0.0.1'});if(csrf){headers.set('Origin',origin);headers.set('X-Arrivo-Request','1');}if(cookie)headers.set('Cookie',cookie);const response=await worker.fetch(new Request(origin+'/api'+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),env);return{status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0],headers:response.headers};};
 const post=(path,body,cookie,extra={})=>call(path,{method:'POST',body,cookie,...extra});
 assert.equal((await call('/health')).status,200);
 assert.equal((await call('/catalog')).status,401);
 assert.equal((await post('/auth/setup',{name:'Owner',password:'CorrectHorse2026!'})).status,401);
 await assert.rejects(createAdmin(DB,{email:'owner@example.test',name:'Owner',password:'short'}),/12 caracteres/);
 const owner=await createAdmin(DB,{email:'Owner@Example.test',name:'Owner',password:'CorrectHorse2026!'});assert.equal(owner.email,'owner@example.test');assert.equal(owner.role,'admin');
 await assert.rejects(createAdmin(DB,{email:'second@example.test',name:'Second',password:'CorrectHorse2026!'}),/Já existe uma conta/);
 assert((await DB.prepare("SELECT count(*) AS n FROM records WHERE kind='track'").first()).n>0);
 const setup=await post('/auth/login',{email:'owner@example.test',password:'CorrectHorse2026!'});assert.equal(setup.status,200,JSON.stringify(setup.body));const admin=setup.cookie;
 assert.match(setup.headers.get('set-cookie'),/^__Host-arrivo=.*HttpOnly; Secure; SameSite=Strict/);
 assert.equal((await call('/catalog',{cookie:admin})).body.records.filter(r=>r.kind==='lesson').length,0);
 assert.equal((await post('/admin/invites',{email:'student@example.test'},admin,{csrf:false})).status,403);
 const nextYear=new Date(Date.now()+365*86400000).toISOString().slice(0,10);
 const invite=await post('/admin/invites',{email:'student@example.test',role:'student',access:{courseExpires:nextYear}},admin);assert.equal(invite.status,200);
 assert.equal((await post('/auth/activate',{token:invite.body.token,name:'Student',password:'StudentPassword2026!'})).status,200);
 assert.equal((await post('/auth/activate',{token:invite.body.token,name:'Student',password:'StudentPassword2026!'})).status,400);
 const login=await post('/auth/login',{email:'student@example.test',password:'StudentPassword2026!'});assert.equal(login.status,200);const student=login.cookie;
 assert.equal((await call('/admin/records',{cookie:student})).status,403);
 assert.equal((await post('/admin/records',{kind:'module',title:'Injection',status:'published'},student)).status,403);
 assert.equal((await post('/admin/records',{kind:'module',title:'Sem categoria',status:'published'},admin)).status,400);
 const category=await post('/admin/records',{kind:'category',title:'Testes',status:'published'},admin);assert.equal(category.status,200);
 const module=await post('/admin/records',{kind:'module',title:'Test module',categoryId:category.body.id,status:'published',order:0},admin);assert.equal(module.status,200);
 const lessonBody={kind:'lesson',title:'Test lesson',moduleId:module.body.id,description:'Plain text',status:'published',videoUrl:'https://youtu.be/dQw4w9WgXcQ',tasks:[{id:'task-1',title:'Learn'}],order:0};
 assert.equal((await post('/admin/records',{...lessonBody,videoUrl:'javascript:alert(1)'},admin)).status,400);
 assert.equal((await post('/admin/records',{...lessonBody,videoUrl:''},admin)).status,400);
 const lesson=await post('/admin/records',lessonBody,admin);assert.equal(lesson.status,200,JSON.stringify(lesson.body));const id=lesson.body.id;
 const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jD1sAAAAASUVORK5CYII=';
 const trackBody={kind:'track',title:'Test track',groups:[['Stage',[module.body.id]]],status:'published',backgroundImage:image};
 const track=await post('/admin/records',trackBody,admin);assert.equal(track.status,200);
 assert.equal((await call('/catalog',{cookie:student})).body.records.find(r=>r.id===track.body.id).backgroundImage,image);
 assert.equal((await post('/admin/records',{...trackBody,backgroundImage:'data:image/svg+xml;base64,PHN2Zz4='},admin)).status,400);
 assert.equal((await post('/admin/records',{...trackBody,backgroundImage:'data:image/png;base64,YmFk'},admin)).status,400);
 assert.equal((await call('/admin/records/'+track.body.id,{method:'PUT',body:{...trackBody,backgroundImage:'',revision:1},cookie:admin})).status,200);
 assert.equal((await call('/catalog',{cookie:student})).body.records.find(r=>r.id===track.body.id).backgroundImage,'');
 assert.equal((await call('/admin/records/'+track.body.id,{method:'PUT',body:{...trackBody,revision:2},cookie:admin})).status,200);
 assert.equal((await call('/catalog',{cookie:student})).body.records.find(r=>r.id===track.body.id).backgroundImage,image);
 const catalog=await call('/catalog',{cookie:student});assert(catalog.body.records.some(l=>l.id===id));
 const save=async(key,value,cookie=student)=>call('/learner',{method:'PUT',body:{key,value},cookie});
 assert.equal((await save('note:'+id,'My private note')).status,200);
 assert.equal((await save('complete:'+id,true)).status,200);
 assert.equal((await call('/learner',{cookie:student})).body.data['note:'+id],'My private note');
 assert.equal((await call('/learner',{cookie:admin})).body.data['note:'+id],undefined);
 assert.equal((await save('note:missing','Bad')).status,400);
 const q=await post('/questions',{lessonId:id,text:'How does it work?'},student);assert.equal(q.status,200);
 const questions=(await call('/admin/records',{cookie:admin})).body.records.filter(r=>r.kind==='question');assert.equal(questions.length,1);
 assert.equal((await call('/questions',{cookie:admin})).body.questions.length,0);
 assert.equal((await call('/admin/records/'+questions[0].id,{method:'PUT',body:{answer:'Here is the answer',revision:1},cookie:admin})).status,200);
 assert.equal((await call('/questions',{cookie:student})).body.questions[0].answer,'Here is the answer');
 assert.equal((await call('/admin/records/'+id,{method:'PUT',body:{...lessonBody,status:'draft',revision:1},cookie:admin})).status,200);
 assert.equal((await call('/admin/records/'+id,{method:'PUT',body:{...lessonBody,status:'published',revision:1},cookie:admin})).status,409);
 assert(!(await call('/catalog',{cookie:student})).body.records.some(r=>r.id===id));
 const event={kind:'event',title:'Live class',status:'published',start:'2026-12-01T10:00:00Z',end:'2026-12-01T11:00:00Z',joinUrl:'https://example.com/event'};
 assert.equal((await post('/admin/records',{...event,end:event.start},admin)).status,400);
 assert.equal((await post('/admin/records',event,admin)).status,200);
 const users=(await call('/admin/users',{cookie:admin})).body.users;const stu=users.find(u=>u.email==='student@example.test');
 assert.equal((await call('/admin/users/owner',{method:'PUT',body:{role:'student',status:'suspended'},cookie:admin})).status,400);
 assert.equal((await call('/admin/users/'+stu.id,{method:'PUT',body:{role:'student',status:'suspended'},cookie:admin})).status,200);
 assert.equal((await call('/catalog',{cookie:student})).status,401);
 assert.equal((await post('/auth/login',{email:stu.email,password:'StudentPassword2026!'})).status,401);
 await call('/admin/users/'+stu.id,{method:'PUT',body:{role:'student',status:'active'},cookie:admin});
 const reset=await post('/admin/invites',{email:stu.email,kind:'reset'},admin);
 assert.equal((await post('/auth/activate',{token:reset.body.token,name:'Student',password:'NewStudentPassword2026!'})).status,200);
 assert.equal((await post('/auth/login',{email:stu.email,password:'NewStudentPassword2026!'})).status,200);
 assert.equal((await post('/auth/login',{email:stu.email,password:'StudentPassword2026!'})).status,401);
 assert((await call('/admin/audit',{cookie:admin})).body.entries.length>0);
 assert.equal((await post('/auth/logout',{},admin)).status,200);
 assert.equal((await call('/admin/records',{cookie:admin})).status,401);
 const again=(await post('/auth/login',{email:'owner@example.test',password:'CorrectHorse2026!'})).cookie;
 await resetPassword(DB,'owner@example.test','RecoveredOwner2026!');
 assert.equal((await call('/admin/records',{cookie:again})).status,401);
 assert.equal((await post('/auth/login',{email:'owner@example.test',password:'RecoveredOwner2026!'})).status,200);
 DB.raw.close();
});
