import bcrypt from 'bcryptjs';
import seed from './seed.json' with {type:'json'};
import {stripeRequest,verifyWebhook} from './stripe.js';
import fs from 'node:fs/promises';
import nodePath from 'node:path';
import {importTrack,catalogFiles} from './catalog.js';
import {salesSchema,maintenanceSchema,defaultContent,defaultMaintenance,cleanContent,withDefaults,ContentError,renderSalesPage,renderLegal,renderMaintenance,adminBanner} from './sales-page.js';

const cookieName='__Host-arrivo';
const now=()=>Math.floor(Date.now()/1000);
const uid=()=>crypto.randomUUID();
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
class HttpError extends Error{constructor(status,message,code){super(message);this.status=status;this.code=code;}}
const fail=(status,message,code)=>{throw new HttpError(status,message,code);};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff',...headers}});
const stmt=(db,sql,...args)=>db.prepare(sql).bind(...args);
const run=(db,sql,...args)=>stmt(db,sql,...args).run();
const first=(db,sql,...args)=>stmt(db,sql,...args).first();
const all=async(db,sql,...args)=>(await stmt(db,sql,...args).all()).results;
const text=(v,min=0,max=500)=>{if(typeof v!=='string'||v.trim().length<min||v.length>max)fail(400,`Preencha os campos corretamente (até ${max} caracteres).`);return v.trim();};
const email=v=>{v=text(v,3,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))fail(400,'Informe um e-mail válido.');return v;};
const password=v=>{if(typeof v!=='string'||v.length<12||bcrypt.truncates(v))fail(400,'Use uma senha com pelo menos 12 caracteres e no máximo 72 bytes.');return v;};
const cleanUser=u=>({id:u.id,email:u.email,name:u.name,role:u.role,status:u.status,created:u.created});
const audit=(db,u,action,target)=>stmt(db,'INSERT INTO audit(id,actor,action,target,created) VALUES(?,?,?,?,?)',uid(),u.id,action,target,now());
const readRecord=r=>({...JSON.parse(r.body),id:r.id,kind:r.kind,status:r.status,revision:r.revision,updated:r.updated});
// Duração da aula: "HH:MM:SS" (ou "HH:MM") vinda do painel, guardada em segundos; minutos arredondados para cima por compatibilidade.
// durationSource 'panel' indica que a duração real foi informada e não deve ser trocada pela estimativa de uma reimportação.
function lessonDuration(b){
 if(b.durationTime!==undefined&&b.durationTime!==''){const m=/^(\d{1,2}):([0-5]\d)(?::([0-5]\d))?$/.exec(String(b.durationTime));if(!m)fail(400,'Informe a duração no formato HH:MM:SS.');const s=Number(m[1])*3600+Number(m[2])*60+Number(m[3]||0);if(s>12*3600)fail(400,'A duração máxima de uma aula é 12 horas.');return{durationSeconds:s,duration:Math.ceil(s/60),durationSource:'panel'};}
 const minutes=Math.max(0,Math.min(999,Number(b.duration)||0));return{duration:minutes,durationSeconds:minutes*60};
}
// Links de consulta da aula: aceita http e https (há sites públicos ainda sem https), nunca outros protocolos.
function linkValue(v){let u;try{u=new URL(String(v||'').trim());}catch{fail(400,'Informe um link válido, começando com https://.');}if(!['https:','http:'].includes(u.protocol)||u.username||u.password)fail(400,'Use um link http ou https sem credenciais.');return u.href;}
function urlValue(v){if(!v)return '';let u;try{u=new URL(v);}catch{fail(400,'Informe um endereço HTTPS válido.');}if(u.protocol!=='https:'||u.username||u.password)fail(400,'Use um endereço HTTPS sem credenciais.');return u.href;}
export function videoSource(value){const s=urlValue(value);if(!s)return null;const u=new URL(s),host=u.hostname.toLowerCase();if(['www.youtube.com','youtube.com','youtu.be','www.youtube-nocookie.com'].includes(host)){const id=host==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').pop();if(!/^[a-zA-Z0-9_-]{11}$/.test(id))fail(400,'Link do YouTube inválido.');return{type:'iframe',url:'https://www.youtube-nocookie.com/embed/'+id};}if(['vimeo.com','www.vimeo.com','player.vimeo.com'].includes(host)){const id=u.pathname.split('/').filter(Boolean).pop();if(!/^\d+$/.test(id))fail(400,'Link do Vimeo inválido.');return{type:'iframe',url:'https://player.vimeo.com/video/'+id};}if(/\.mp4$/i.test(u.pathname))return{type:'video',url:s};fail(400,'Use um vídeo do YouTube, Vimeo ou um arquivo MP4 em HTTPS.');}
async function body(req){const raw=await req.text(),path=new URL(req.url).pathname,limit=path.startsWith('/api/planner/attachments')?2900000:path.startsWith('/api/admin/records')?850000:100000;if(raw.length>limit)fail(413,'Conteúdo muito grande.');try{return JSON.parse(raw);}catch{fail(400,'Dados inválidos.');}}
async function rate(db,key,max=12){const t=now();const row=await stmt(db,'INSERT INTO limits(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN until<? THEN 1 ELSE count+1 END,until=CASE WHEN until<? THEN excluded.until ELSE until END RETURNING count',key,t+900,t,t).first();if(row.count>max)fail(429,'Muitas tentativas. Aguarde 15 minutos e tente novamente.');}
async function session(req,db){const raw=req.headers.get('cookie')||'';const value=raw.split(';').map(s=>s.trim()).find(s=>s.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(!value||!/^[a-f0-9]{64}$/.test(value))return null;return first(db,'SELECT users.*,sessions.token AS session_token FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token=? AND sessions.expires>? AND users.status=?',await hash(value),now(),'active');}
async function loginResponse(db,u){const value=token();await db.batch([stmt(db,'DELETE FROM sessions WHERE expires<?',now()),stmt(db,'INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)',await hash(value),u.id,now()+86400)]);return json({user:cleanUser(u),access:await accessOf(db,u)},200,{'Set-Cookie':`${cookieName}=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=86400`});}
const clientIp=req=>req.headers.get('x-arrivo-client-ip')||'unknown';
async function initializeCatalog(db){const statements=seed.map(r=>stmt(db,'INSERT OR IGNORE INTO records(id,kind,body,status,revision,updated) VALUES(?,?,?,?,1,?)',r.id,r.kind,JSON.stringify(r.body),r.status,now()));for(let i=0;i<statements.length;i+=30)await db.batch(statements.slice(i,i+30));for(const file of await catalogFiles())await importTrack(db,JSON.parse(await fs.readFile(file,'utf8')),nodePath.resolve('data','files'));}
// Acesso: o curso libera a plataforma por um período; Planner e Fornitore são extras que nunca passam da validade do curso.
const products=['course','planner','fornitore'];
const lockedMessage={course:'Seu acesso ao Arrivo In Itália não está ativo. Renove para continuar.',planner:'O Planner é um adicional que ainda não faz parte do seu acesso.',fornitore:'O Fornitore é um adicional que ainda não faz parte do seu acesso.'};
async function accessOf(db,u){
 if(u.role==='admin')return Object.fromEntries(products.map(p=>[p,{active:true,expires:null}]));
 const t=now(),rows=await all(db,"SELECT product,max(expires) AS expires FROM entitlements WHERE user_id=? AND status='active' AND starts<=? AND expires>? GROUP BY product",u.id,t,t);
 const current=Object.fromEntries(rows.map(r=>[r.product,r.expires])),course=current.course||null;
 const last=course?null:(await first(db,"SELECT max(expires) AS expires FROM entitlements WHERE user_id=? AND product='course' AND status='active'",u.id))?.expires||null;
 const access={course:{active:!!course,expires:course,expired:last}};
 for(const p of ['planner','fornitore']){const expires=course&&current[p]?Math.min(course,current[p]):null;access[p]={active:!!expires,expires};}
 return access;
}
// Validade informada como data (AAAA-MM-DD) vale até o fim do dia no horário de Brasília.
function endOfDay(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))fail(400,'Informe a validade no formato de data.');const t=Date.parse(v+'T23:59:59-03:00')/1000;if(!Number.isFinite(t))fail(400,'Data de validade inválida.');if(t<=now())fail(400,'Informe uma data de validade futura.');if(t>now()+5*366*86400)fail(400,'A validade máxima é de cinco anos.');return t;}
function accessSpec(b){if(!b||typeof b!=='object')fail(400,'Dados de acesso inválidos.');return{courseExpires:b.courseExpires?endOfDay(b.courseExpires):null,planner:b.planner===true,fornitore:b.fornitore===true};}
// Ajusta o acesso para o estado pedido: um único registro ativo por produto, mantendo os anteriores como revogados.
async function setAccess(db,userId,spec,actor,source){
 const t=now(),target=spec.courseExpires,current=await all(db,"SELECT * FROM entitlements WHERE user_id=? AND status='active' AND expires>?",userId,t),statements=[],changes=[];
 for(const product of products){
  const wanted=!!target&&(product==='course'||spec[product]===true),rows=current.filter(r=>r.product===product);
  if(wanted?rows.length===1&&rows[0].expires===target&&rows[0].starts<=t:!rows.length)continue;
  for(const r of rows)statements.push(stmt(db,"UPDATE entitlements SET status='revoked',updated=? WHERE id=?",t,r.id));
  if(wanted)statements.push(stmt(db,'INSERT INTO entitlements(id,user_id,product,starts,expires,status,source,reference,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?)',uid(),userId,product,Math.min(t,...rows.map(r=>r.starts)),target,'active',source,actor?.id||null,t,t));
  changes.push(product+':'+(wanted?new Date((target-3*3600)*1000).toISOString().slice(0,10):'removido'));
 }
 if(statements.length&&actor)statements.push(audit(db,actor,'access:'+changes.join(','),userId));
 if(statements.length)await db.batch(statements);
 return changes;
}
const publicProvider=r=>{const{email,phone,...rest}=r;return rest;};

// Materiais da aula. O tipo vem da extensão e é conferido pela assinatura do arquivo quando o formato tem uma.
const lessonFileTypes={pdf:'application/pdf',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xls:'application/vnd.ms-excel',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',ppt:'application/vnd.ms-powerpoint',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',odt:'application/vnd.oasis.opendocument.text',ods:'application/vnd.oasis.opendocument.spreadsheet',odp:'application/vnd.oasis.opendocument.presentation',rtf:'application/rtf',txt:'text/plain; charset=utf-8',csv:'text/csv; charset=utf-8',zip:'application/zip',mp3:'audio/mpeg',m4a:'audio/mp4'};
const zipBased=['docx','xlsx','pptx','odt','ods','odp','zip'],oleBased=['doc','xls','ppt'];
const maxLessonFile=25*1024*1024,maxLessonFiles=15;
function lessonFileType(name,bytes){
 const ext=(name.split('.').pop()||'').toLowerCase(),type=lessonFileTypes[ext];if(!type||!name.includes('.'))fail(400,'Formato não permitido. Use PDF, imagens, documentos do Office/LibreOffice, TXT, CSV, ZIP ou MP3.');
 const starts=sig=>sig.every((b,i)=>bytes[i]===b),ascii=s=>[...s].map(c=>c.charCodeAt(0));
 const ok=ext==='pdf'?starts(ascii('%PDF-')):ext==='png'?starts([0x89,0x50,0x4e,0x47]):['jpg','jpeg'].includes(ext)?starts([0xff,0xd8,0xff]):ext==='webp'?starts(ascii('RIFF'))&&String.fromCharCode(...bytes.slice(8,12))==='WEBP':ext==='gif'?starts(ascii('GIF8')):zipBased.includes(ext)?starts([0x50,0x4b,0x03,0x04]):oleBased.includes(ext)?starts([0xd0,0xcf,0x11,0xe0]):ext==='rtf'?starts(ascii('{\\rtf')):ext==='mp3'?starts(ascii('ID3'))||(bytes[0]===0xff&&(bytes[1]&0xe0)===0xe0):true;
 if(!ok)fail(400,'O conteúdo do arquivo não corresponde à extensão .'+ext+'.');
 return type;
}
const filesDir=env=>env.FILES_DIR||nodePath.resolve('data','files');
const inlineTypes=t=>t==='application/pdf'||t.startsWith('image/')||t.startsWith('audio/');
async function lessonFilesOf(db,ids){if(!ids.length)return{};const rows=await all(db,`SELECT id,lesson_id AS lessonId,name,type,size FROM lesson_files WHERE lesson_id IN (${ids.map(()=>'?').join(',')}) ORDER BY position,created`,...ids);const map={};for(const r of rows)(map[r.lessonId]||=[]).push({id:r.id,name:r.name,type:r.type,size:r.size});return map;}

// Vendas. Preços em centavos de real; o curso dá acesso por accessDays dias.
const saleDefaults={coursePrice:99700,plannerPrice:19700,fornitorePrice:29700,renewalDiscount:20,renewalWindowDays:60,accessDays:365};
const renewalLeadDays=60;
const saleNames={course:'Curso Arrivo In Itália (1 ano de acesso)',planner:'Adicional Meu Planner',fornitore:'Adicional Fornitore'};
async function saleSettings(db){const s={...saleDefaults};for(const r of await all(db,"SELECT key,value FROM settings WHERE key LIKE 'sale.%'")){const k=r.key.slice(5);if(k in s)s[k]=Number(r.value);}return s;}
// O que a pessoa pode comprar agora e por quanto. u pode ser nulo (visitante).
async function offerFor(db,u){
 const s=await saleSettings(db),t=now(),prices={course:s.coursePrice,planner:s.plannerPrice,fornitore:s.fornitorePrice};
 if(!u)return{kind:'new',prices,total:prices,discountPercent:0,available:products,activeExtras:[],courseActive:false};
 const a=await accessOf(db,u),last=(await first(db,"SELECT max(expires) AS expires FROM entitlements WHERE user_id=? AND product='course' AND status='active'",u.id))?.expires||null;
 const canRenew=!a.course.active||a.course.expires-t<=renewalLeadDays*86400;
 const discount=last&&canRenew&&s.renewalDiscount>0&&(!s.renewalWindowDays||t<=last+s.renewalWindowDays*86400)?s.renewalDiscount:0;
 const course=Math.round(prices.course*(100-discount)/100);
 const extras=['planner','fornitore'].filter(p=>!a[p].active||canRenew);
 return{kind:last?'renewal':'new',prices,total:{...prices,course},discountPercent:discount,available:[...(canRenew?['course']:[]),...(a.course.active||canRenew?extras:[])],activeExtras:['planner','fornitore'].filter(p=>a[p].active),courseActive:a.course.active,courseExpires:a.course.expires,renewalOpens:a.course.active&&!canRenew?a.course.expires-renewalLeadDays*86400:null};
}
function purchaseProducts(value,offer,addon){
 if(!Array.isArray(value)||!value.length)fail(400,'Escolha o que deseja comprar.');
 const list=[...new Set(value)];if(list.some(p=>!products.includes(p)))fail(400,'Produto inválido.');
 if(!list.includes('course')&&(!addon||!offer.courseActive))fail(400,'Os adicionais são vendidos junto com o curso.');
 if(!list.includes('course')&&offer.activeExtras.some(p=>list.includes(p)))fail(400,'Este adicional já faz parte do seu acesso.');
 for(const p of list)if(!offer.available.includes(p))fail(400,p==='course'?'A renovação fica disponível nos 60 dias anteriores ao vencimento do seu acesso.':'Este adicional já faz parte do seu acesso ou exige o curso ativo.');
 return products.filter(p=>list.includes(p));
}
async function createCheckout(env,db,req,{email,name,userId,kind,items,offer}){
 const id=uid(),origin=new URL(req.url).origin,amounts=items.map(p=>offer.total[p]),amount=amounts.reduce((a,b)=>a+b,0),discount=items.includes('course')?offer.prices.course-offer.total.course:0;
 const session=await stripeRequest(env,'POST','/checkout/sessions',{mode:'payment',locale:'pt-BR',customer_email:email,client_reference_id:id,metadata:{order_id:id},payment_intent_data:{metadata:{order_id:id}},success_url:`${origin}/compra?pedido=${id}&session_id={CHECKOUT_SESSION_ID}`,cancel_url:userId?`${origin}/app#perfil`:`${origin}/#comprar`,line_items:Object.fromEntries(items.map((p,i)=>[i,{quantity:1,price_data:{currency:'brl',unit_amount:amounts[i],product_data:{name:saleNames[p]+(p==='course'&&discount?` (renovação com ${offer.discountPercent}% de desconto)`:'')}}}]))});
 await run(db,'INSERT INTO orders(id,user_id,email,name,kind,products,amount,discount,currency,status,stripe_session,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',id,userId||null,email,name,kind,JSON.stringify(items),amount,discount,'brl','pending',session.id,now(),now());
 return{url:session.url,order:id};
}
// Libera o acesso de um pedido pago. Idempotente: só o primeiro aviso de pagamento tem efeito.
async function fulfillOrder(db,orderId,paymentIntent){
 const t=now(),claim=await run(db,"UPDATE orders SET status='paid',paid_at=?,updated=?,stripe_payment_intent=coalesce(?,stripe_payment_intent) WHERE id=? AND status IN ('pending','failed','expired')",t,t,paymentIntent||null,orderId);
 if(!claim.meta.changes)return;
 const order=await first(db,'SELECT * FROM orders WHERE id=?',orderId);
 try{
  let user=order.user_id?await first(db,'SELECT * FROM users WHERE id=?',order.user_id):await first(db,'SELECT * FROM users WHERE email=?',order.email);const statements=[];
  if(!user){user={id:uid(),email:order.email,name:order.name,role:'student'};statements.push(stmt(db,'INSERT INTO users(id,email,name,password,role,status,created) VALUES(?,?,?,NULL,?,?,?)',user.id,user.email,user.name,'student','active',t));}
  const s=await saleSettings(db),items=JSON.parse(order.products),grant=(product,starts,expires)=>statements.push(stmt(db,'INSERT INTO entitlements(id,user_id,product,starts,expires,status,source,reference,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?)',uid(),user.id,product,starts,expires,'active','stripe',order.id,t,t));
  let start=t,end;
  if(items.includes('course')){const current=(await first(db,"SELECT max(expires) AS expires FROM entitlements WHERE user_id=? AND product='course' AND status='active' AND expires>?",user.id,t))?.expires;start=Math.max(t,current||0);end=start+s.accessDays*86400;grant('course',start,end);}
  else{end=(await accessOf(db,user)).course.expires;if(!end)throw new Error('Adicional pago sem curso ativo.');}
  for(const p of items.filter(p=>p!=='course'))grant(p,items.includes('course')?start:t,end);
  statements.push(stmt(db,'UPDATE orders SET user_id=? WHERE id=?',user.id,order.id));
  await db.batch(statements);
 }catch(e){await run(db,"UPDATE orders SET status='pending',paid_at=NULL WHERE id=?",orderId);throw e;}
}
async function syncOrder(env,db,order){
 if(order.status!=='pending'||!order.stripe_session||!env.STRIPE_SECRET_KEY)return order;
 const session=await stripeRequest(env,'GET','/checkout/sessions/'+encodeURIComponent(order.stripe_session));
 if(session.payment_status==='paid'){await fulfillOrder(db,order.id,session.payment_intent);return first(db,'SELECT * FROM orders WHERE id=?',order.id);}
 return order;
}
// Link para o comprador criar a senha. Gerado sob demanda; tokens anteriores do mesmo tipo deixam de valer.
async function welcomeLink(db,req,email){const raw=token();await db.batch([stmt(db,"UPDATE invites SET used=1 WHERE email=? AND kind='welcome'",email),stmt(db,'INSERT INTO invites(token,email,role,kind,expires,used) VALUES(?,?,?,?,?,0)',await hash(raw),email,'student','welcome',now()+7*86400)]);return new URL(req.url).origin+'/app#ativar?token='+raw;}
async function stripeWebhook(req,env){
 const db=env.DB,raw=await req.text();if(raw.length>1000000)fail(413,'Conteúdo muito grande.');
 if(!await verifyWebhook(env,raw,req.headers.get('stripe-signature')))fail(400,'Assinatura inválida.');
 const event=JSON.parse(raw),object=event.data?.object||{},orderId=object.metadata?.order_id||object.client_reference_id;
 if(event.type.startsWith('checkout.session.')){
  const order=orderId&&await first(db,'SELECT * FROM orders WHERE id=? AND stripe_session=?',orderId,object.id);
  if(!order)return json({received:true,ignored:true});
  if(['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(event.type)&&object.payment_status==='paid')await fulfillOrder(db,order.id,object.payment_intent);
  else if(event.type==='checkout.session.completed')await run(db,'UPDATE orders SET stripe_payment_intent=?,updated=? WHERE id=?',object.payment_intent||null,now(),order.id);
  else if(event.type==='checkout.session.async_payment_failed')await run(db,"UPDATE orders SET status='failed',updated=? WHERE id=? AND status='pending'",now(),order.id);
  else if(event.type==='checkout.session.expired')await run(db,"UPDATE orders SET status='expired',updated=? WHERE id=? AND status='pending'",now(),order.id);
 }
 if(event.type==='charge.refunded'&&object.payment_intent){
  const order=await first(db,"SELECT * FROM orders WHERE stripe_payment_intent=? AND status='paid'",object.payment_intent);
  if(order&&object.amount_refunded>=object.amount)await db.batch([stmt(db,"UPDATE orders SET status='refunded',updated=? WHERE id=?",now(),order.id),stmt(db,"UPDATE entitlements SET status='revoked',updated=? WHERE reference=? AND source='stripe'",now(),order.id)]);
 }
 return json({received:true});
}
// Página de vendas: versões (rascunho/publicada/arquivadas) e status do site (publicada ou em manutenção).
async function salesVersion(db,status){const r=await first(db,'SELECT * FROM sales_page_versions WHERE status=? ORDER BY updated DESC LIMIT 1',status);return r?{...r,content:withDefaults(salesSchema,JSON.parse(r.content),defaultContent)}:null;}
async function salesState(db){const m=Object.fromEntries((await all(db,"SELECT key,value FROM settings WHERE key IN ('site.mode','site.modeSince','site.maintenance')")).map(r=>[r.key,r.value]));return{mode:m['site.mode']==='maintenance'?'maintenance':'published',modeSince:Number(m['site.modeSince'])||null,maintenance:withDefaults(maintenanceSchema,m['site.maintenance']?JSON.parse(m['site.maintenance']):null,defaultMaintenance)};}
const putSetting=(db,key,value)=>stmt(db,'INSERT INTO settings(key,value,updated) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated=excluded.updated',key,value,now());
function cleanOrFail(schema,value,assets){try{return cleanContent(schema,value,'',assets);}catch(e){if(e instanceof ContentError)fail(400,e.message);throw e;}}
async function salesPaused(db){if((await salesState(db)).mode==='maintenance')fail(503,'As compras estão temporariamente suspensas enquanto atualizamos a página. Tente novamente em breve.','sales_paused');}
async function upsertDraft(db,content,authorId){const t=now(),d=await first(db,"SELECT id FROM sales_page_versions WHERE status='draft'");await(d?run(db,'UPDATE sales_page_versions SET content=?,author_id=?,updated=? WHERE id=?',JSON.stringify(content),authorId,t,d.id):run(db,'INSERT INTO sales_page_versions(id,status,content,author_id,created,updated) VALUES(?,?,?,?,?,?)',uid(),'draft',JSON.stringify(content),authorId,t,t));return t;}
// Aceita "1.297,90", "1297,90" e "1297.90".
const reais=v=>{const s=String(v).trim().replace(/^R\$\s*/,''),n=Number(s.includes(',')?s.replace(/\./g,'').replace(',','.'):s);if(!Number.isFinite(n)||n<1||n>100000)fail(400,'Informe preços entre R$ 1 e R$ 100.000.');return Math.round(n*100);};

function validateTrackImage(value){
 if(value===undefined||value==='')return '';
 if(typeof value!=='string'||value.length>683000)fail(400,'A imagem deve ter até 500 KB.');
 const match=/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/]+={0,2})$/.exec(value);
 if(!match)fail(400,'Use uma imagem JPG, PNG ou WebP.');
 let bytes;try{bytes=atob(match[2]);}catch{fail(400,'Imagem inválida.');}
 if(bytes.length>512000)fail(400,'A imagem deve ter até 500 KB.');
 const valid=match[1]==='png'?bytes.startsWith('\x89PNG\r\n\x1a\n'):match[1]==='jpeg'?bytes.startsWith('\xff\xd8\xff'):bytes.startsWith('RIFF')&&bytes.slice(8,12)==='WEBP';
 if(!valid)fail(400,'Arquivo de imagem inválido.');return value;
}


// Tarefas do planner de uma trilha: as do modelo publicado em Gestão do Planner ou, sem modelo, uma por módulo da trilha.
async function plannerTasks(db,trackRow){const template=await first(db,"SELECT body FROM records WHERE kind='planner' AND status='published' AND json_extract(body,'$.trackId')=?",trackRow.id);if(template)return JSON.parse(template.body).items.map(i=>({id:i.id,title:i.title,phase:i.phase}));const track=JSON.parse(trackRow.body);return track.groups.flatMap(([phase,ids])=>ids.map(id=>({id,phase})));}
async function plannerTarget(db,trackId,itemId){const row=await first(db,"SELECT * FROM records WHERE id=? AND kind='track' AND status='published'",trackId);if(!row)fail(400,'Trilha indisponível.');if(!(await plannerTasks(db,row)).some(t=>t.id===itemId))fail(400,'Etapa indisponível.');return row;}
function attachmentData(value){if(typeof value!=='string'||value.length>2800000)fail(400,'O arquivo deve ter até 2 MB.');const match=/^data:(application\/pdf|image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/]+={0,2})$/.exec(value);if(!match)fail(400,'Envie um arquivo PDF, JPG, PNG ou WebP.');let bytes;try{bytes=atob(match[2]);}catch{fail(400,'Arquivo inválido.');}if(bytes.length>2097152)fail(400,'O arquivo deve ter até 2 MB.');const valid=match[1]==='application/pdf'?bytes.startsWith('%PDF-'):match[1]==='image/png'?bytes.startsWith('\x89PNG\r\n\x1a\n'):match[1]==='image/jpeg'?bytes.startsWith('\xff\xd8\xff'):bytes.startsWith('RIFF')&&bytes.slice(8,12)==='WEBP';if(!valid)fail(400,'O conteúdo do arquivo não corresponde ao formato informado.');return{type:match[1],data:match[2],size:bytes.length};}
function attachmentResponse(row,download=false){const binary=atob(row.data),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const fallback=row.type==='application/pdf'?'documento.pdf':row.type==='image/png'?'imagem.png':row.type==='image/webp'?'imagem.webp':'imagem.jpg',name=(row.name||fallback).replace(/[\r\n"\\/]/g,'_');return new Response(bytes,{headers:{'Content-Type':row.type,'Content-Length':String(row.size),'Content-Disposition':`${download?'attachment':'inline'}; filename="${name}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
async function validatePlanner(db,trackId,value){

 const row=await first(db,"SELECT * FROM records WHERE id=? AND kind='track' AND status='published'",trackId);if(!row)fail(400,'Trilha indisponível.');
 if(!value||typeof value!=='object'||Array.isArray(value)||!Array.isArray(value.items)||value.items.length>100)fail(400,'Planner inválido.');
 const allowed=new Set((await plannerTasks(db,row)).map(t=>t.id));if(value.items.length!==new Set(value.items.map(i=>i.id)).size)fail(400,'Etapas duplicadas.');
 const statuses=new Set(['not_started','organizing','waiting','in_progress','blocked','done']),priorities=new Set(['low','normal','high']),currencies=new Set(['EUR','BRL']);
 const clean=[];for(const item of value.items){const id=text(item.id,1,100);if(!allowed.has(id))fail(400,'Etapa indisponível.');const status=statuses.has(item.status)?item.status:'not_started',priority=priorities.has(item.priority)?item.priority:'normal',currency=currencies.has(item.currency)?item.currency:'EUR';const dateValue=v=>{if(!v)return '';if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v)))fail(400,'Data inválida.');return v;};const cost=item.cost===''||item.cost==null?'':Number(item.cost);if(cost!==''&&(!Number.isFinite(cost)||cost<0||cost>9999999))fail(400,'Custo inválido.');clean.push({id,title:text(item.title||'',0,160),phase:text(item.phase||'',0,160),status,responsible:text(item.responsible||'',0,120),issuanceDate:dateValue(item.issuanceDate),dueDate:dateValue(item.dueDate),cost,currency,priority,documentNumber:text(item.documentNumber||'',0,120),location:text(item.location||'',0,160),attachmentName:text(item.attachmentName||'',0,160),attachmentUrl:urlValue(item.attachmentUrl||''),notes:text(item.notes||'',0,5000),updated:Number.isFinite(Number(item.updated))?Number(item.updated):now()*1000});}
 return{trackId,items:clean,updated:now()*1000};
}
async function validateRecord(db,kind,b,status,id){const base={title:text(b.title,1,160),description:text(b.description||'',0,10000),order:Number.isInteger(Number(b.order))?Number(b.order):0};if(base.order<0||base.order>10000)fail(400,'Ordem inválida.');if(kind==='category')return{...base,showOnHome:b.showOnHome!==false};
 if(kind==='module'){const cardStyle=b.cardStyle==='image'?'image':'symbol',cardImage=validateTrackImage(b.cardImage);if(cardStyle==='image'&&!cardImage)fail(400,'Envie a imagem do cartão ou escolha exibir um símbolo.');const categoryId=text(b.categoryId||'',1,100),cat=await first(db,"SELECT body FROM records WHERE id=? AND kind='category' AND status<>'archived'",categoryId);if(!cat)fail(400,'Escolha uma categoria ativa para o módulo.');return{...base,categoryId,category:JSON.parse(cat.body).title,symbol:text(b.symbol||'◇',1,8),cardStyle,cardImage};}
 if(kind==='lesson'){const moduleId=text(b.moduleId,1,100);const m=await first(db,'SELECT id FROM records WHERE id=? AND kind=? AND status<>?',moduleId,'module','archived');if(!m)fail(400,'Selecione um módulo ativo.');const video=videoSource(b.videoUrl||'');if(status==='published'&&!video)fail(400,'Insira o vídeo antes de publicar a aula.');const tasks=Array.isArray(b.tasks)?b.tasks.map(t=>({id:text(t.id||uid(),1,100),title:text(t.title,1,300)})):[];if(tasks.length>30||new Set(tasks.map(t=>t.id)).size!==tasks.length)fail(400,'Tarefas inválidas.');
  const links=Array.isArray(b.links)?b.links.filter(x=>x&&(x.title||x.url)).map(x=>({title:text(x.title||'',1,160),url:linkValue(x.url)})):[];if(links.length>20)fail(400,'Use no máximo 20 links por aula.');
  const plannerLinks=[];for(const x of Array.isArray(b.plannerTasks)?b.plannerTasks:[]){const trackId=text(x?.trackId||'',1,100),itemId=text(x?.itemId||'',1,100);const track=await first(db,"SELECT * FROM records WHERE id=? AND kind='track' AND status<>'archived'",trackId);if(!track||!(await plannerTasks(db,track)).some(t=>t.id===itemId))fail(400,'Uma das tarefas do planner não está mais disponível.');if(!plannerLinks.some(p=>p.trackId===trackId&&p.itemId===itemId))plannerLinks.push({trackId,itemId});}if(plannerLinks.length>10)fail(400,'Vincule no máximo 10 tarefas do planner.');
  return{...base,moduleId,videoUrl:urlValue(b.videoUrl||''),video,...lessonDuration(b),tasks,links,plannerTasks:plannerLinks};}
 if(kind==='track'){if(!Array.isArray(b.groups)||b.groups.length>25)fail(400,'Organize as etapas da trilha.');const groups=[];for(const g of b.groups){if(!Array.isArray(g)||!Array.isArray(g[1])||g[1].length>30)fail(400,'Etapa inválida.');const ids=[...new Set(g[1])];for(const mid of ids){if(typeof mid!=='string'||!await first(db,'SELECT id FROM records WHERE id=? AND kind=? AND status<>?',mid,'module','archived'))fail(400,'A etapa contém um módulo indisponível.');}groups.push([text(g[0],1,160),ids]);}if(status==='published'&&(!groups.length||!groups.some(g=>g[1].length)))fail(400,'Adicione módulos antes de publicar a trilha.');return{...base,backgroundImage:validateTrackImage(b.backgroundImage),name:base.title,tag:text(b.tag||'SUA JORNADA',0,100),groups};}
 if(kind==='provider'){const price=Number(b.price),duration=Number(b.duration);if(!Number.isFinite(price)||price<0||price>9999999)fail(400,'Preço inválido.');if(!Number.isInteger(duration)||duration<15||duration>480)fail(400,'Duração inválida.');return{...base,name:base.title,brand:text(b.brand||'',0,120),specialty:text(b.specialty,2,120),services:text(b.services||'',0,2000),summary:text(b.summary||'',0,500),bio:text(b.bio||'',0,10000),photo:validateTrackImage(b.photo),price,currency:b.currency==='BRL'?'BRL':'EUR',duration,rating:Math.max(0,Math.min(5,Number(b.rating)||0)),reviewCount:Math.max(0,Math.min(999999,Number(b.reviewCount)||0)),city:text(b.city||'',0,120),languages:text(b.languages||'',0,300),email:email(b.email),phone:text(b.phone||'',0,60),website:urlValue(b.website||''),credentials:text(b.credentials||'',0,3000),availability:text(b.availability||'',0,2000),featured:b.featured===true};}
 if(kind==='planner'){const trackId=text(b.trackId,1,100);if(!await first(db,"SELECT id FROM records WHERE id=? AND kind='track' AND status<>?",trackId,'archived'))fail(400,'Selecione uma trilha ativa.');if(!Array.isArray(b.items)||b.items.length>100)fail(400,'Configure as tarefas do planner.');const priorities=new Set(['low','normal','high']),currencies=new Set(['EUR','BRL']),items=[];for(const raw of b.items){const cost=raw.estimatedCost===''?'':Number(raw.estimatedCost),dueDays=raw.dueDays===''?'':Number(raw.dueDays);if(cost!==''&&(!Number.isFinite(cost)||cost<0||cost>9999999))fail(400,'Custo estimado inválido.');if(dueDays!==''&&(!Number.isInteger(dueDays)||dueDays<0||dueDays>3650))fail(400,'Prazo estimado inválido.');items.push({id:text(raw.id||uid(),1,100),title:text(raw.title,2,160),phase:text(raw.phase,2,160),description:text(raw.description||'',0,2000),responsibleHint:text(raw.responsibleHint||'',0,120),priority:priorities.has(raw.priority)?raw.priority:'normal',estimatedCost:cost,currency:currencies.has(raw.currency)?raw.currency:'EUR',dueDays,requiredDocuments:text(raw.requiredDocuments||'',0,2000),attachmentRequired:raw.attachmentRequired===true,order:Number.isInteger(Number(raw.order))?Math.max(0,Math.min(10000,Number(raw.order))):items.length});}if(new Set(items.map(i=>i.id)).size!==items.length)fail(400,'Existem tarefas duplicadas.');return{...base,trackId,items:items.sort((a,b)=>a.order-b.order)};}
 if(kind==='event'){const start=Date.parse(b.start),end=Date.parse(b.end);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)fail(400,'Informe início e término válidos.');return{...base,start:new Date(start).toISOString(),end:new Date(end).toISOString(),host:text(b.host||'',0,160),location:text(b.location||'',0,300),joinUrl:urlValue(b.joinUrl||'')};}fail(400,'Tipo de conteúdo inválido.');}

// Conta proprietária: criada apenas pelo terminal do servidor (server/cli.js), nunca pela web.
export async function createAdmin(db,{email:rawEmail,name:rawName,password:rawPassword}){const mail=email(rawEmail),name=text(rawName,2,120),pw=password(rawPassword);const r=await run(db,'INSERT INTO users(id,email,name,password,role,status,created) SELECT ?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM users)','owner',mail,name,await bcrypt.hash(pw,12),'admin','active',now());if(!r.meta.changes)fail(409,'Já existe uma conta cadastrada. Convide novos administradores pela área de Administração.');await initializeCatalog(db);return cleanUser(await first(db,'SELECT * FROM users WHERE id=?','owner'));}
export async function resetPassword(db,rawEmail,rawPassword){const mail=email(rawEmail),pw=password(rawPassword);const u=await first(db,'SELECT id FROM users WHERE email=?',mail);if(!u)fail(404,'Conta não encontrada.');await db.batch([stmt(db,'UPDATE users SET password=?,status=? WHERE id=?',await bcrypt.hash(pw,12),'active',u.id),stmt(db,'DELETE FROM sessions WHERE user_id=?',u.id)]);}

async function api(req,env,path){const db=env.DB;if(!db)fail(503,'O armazenamento está indisponível. Tente novamente.');const method=req.method;
 if(path==='/api/health'&&method==='GET'){await first(db,'SELECT 1 AS ok');return json({ok:true});}
 // O Stripe chama este endereço diretamente; a autenticidade vem da assinatura, não da origem.
 if(path==='/api/stripe/webhook'&&method==='POST')return stripeWebhook(req,env);
 if(!['GET','HEAD'].includes(method)){if(req.headers.get('Origin')!==new URL(req.url).origin||req.headers.get('X-Arrivo-Request')!=='1')fail(403,'Solicitação não autorizada. Atualize a página.');const upload=method==='POST'&&(/^\/api\/admin\/lessons\/[^/]+\/files$/.test(path)||path==='/api/admin/site-assets');if(!req.headers.get('content-type')?.startsWith(upload?'application/octet-stream':'application/json'))fail(415,upload?'Envie o arquivo como dados binários.':'Use dados JSON.');}
 if(path==='/api/auth/login'&&method==='POST'){const b=await body(req),mail=email(b.email);await rate(db,'login:'+await hash(mail));await rate(db,'ip:'+await hash(clientIp(req)),60);const u=await first(db,'SELECT * FROM users WHERE email=?',mail);const pw=typeof b.password==='string'&&b.password.length<=200?b.password:'';const valid=await bcrypt.compare(pw,u?.password||'$2b$12$C6UzMDM.H6dfI/f/IKcEe.5SX2x4lqReGVSjtZKfX9NbTXMC63eEq');if(!u||!valid||u.status!=='active')fail(401,'E-mail ou senha inválidos, ou acesso suspenso.');return loginResponse(db,u);}
 if(path==='/api/auth/activate'&&method==='POST'){const b=await body(req);await rate(db,'activate:'+await hash(clientIp(req)),30);const t=text(b.token,64,64),name=text(b.name,2,120),pw=password(b.password);const inv=await first(db,'SELECT * FROM invites WHERE token=? AND used=0 AND expires>?',await hash(t),now());if(!inv)fail(400,'Este link expirou ou já foi utilizado. Solicite um novo ao administrador.');const stored=await bcrypt.hash(pw,12);const existing=await first(db,'SELECT * FROM users WHERE email=?',inv.email);if(inv.kind!=='invite'&&!existing)fail(400,'Conta não encontrada.');if(inv.kind==='welcome'&&existing.password)fail(409,'Sua senha já foi criada. Entre com seu e-mail.');if(inv.kind==='invite'&&existing)fail(409,'Esta conta já existe. Use a recuperação de acesso.');const used=await run(db,'UPDATE invites SET used=1 WHERE token=? AND used=0 AND expires>?',inv.token,now());if(!used.meta.changes)fail(409,'Link já utilizado.');const id=existing?.id||uid();await db.batch([inv.kind==='reset'?stmt(db,'UPDATE users SET password=? WHERE id=?',stored,id):inv.kind==='welcome'?stmt(db,'UPDATE users SET password=?,name=? WHERE id=?',stored,name,id):stmt(db,'INSERT INTO users(id,email,name,password,role,status,created) VALUES(?,?,?,?,?,?,?)',id,inv.email,name,stored,inv.role,'active',now()),stmt(db,'DELETE FROM sessions WHERE user_id=?',id)]);if(inv.kind==='invite'&&inv.grants){const g=JSON.parse(inv.grants);if(g.courseExpires>now())await setAccess(db,id,g,null,'invite');}return json({ok:true,message:'Senha definida. Entre com seu e-mail.'});}
 // Página de vendas: preços, compra por visitante e acompanhamento do pedido.
 if(path==='/api/offer'&&method==='GET'){const viewer=await session(req,db),offer=await offerFor(db,viewer);return json({offer,payments:!!env.STRIPE_SECRET_KEY,paused:(await salesState(db)).mode==='maintenance',signedIn:!!viewer});}
 if(path==='/api/checkout'&&method==='POST'){const b=await body(req);await rate(db,'checkout:'+await hash(clientIp(req)),20);await salesPaused(db);const mail=email(b.email),name=text(b.name,2,120);if(await first(db,'SELECT id FROM users WHERE email=?',mail))fail(409,'Já existe uma conta com este e-mail. Entre na plataforma para renovar ou adicionar itens.','account_exists');const offer=await offerFor(db,null);return json(await createCheckout(env,db,req,{email:mail,name,kind:'new',items:purchaseProducts(b.products,offer,false),offer}));}
 if(path==='/api/checkout/status'&&method==='GET'){const url=new URL(req.url),id=text(url.searchParams.get('pedido')||'',1,100),sid=text(url.searchParams.get('session')||'',1,300);await rate(db,'status:'+await hash(clientIp(req)),120);let order=await first(db,'SELECT * FROM orders WHERE id=? AND stripe_session=?',id,sid);if(!order)fail(404,'Pedido não encontrado.');order=await syncOrder(env,db,order);const buyer=order.user_id&&await first(db,'SELECT * FROM users WHERE id=?',order.user_id);return json({status:order.status,email:order.email,kind:order.kind,products:JSON.parse(order.products),amount:order.amount,activationUrl:order.status==='paid'&&buyer&&!buyer.password?await welcomeLink(db,req,buyer.email):null});}
 const u=await session(req,db);if(!u)fail(401,'Entre na sua conta para continuar.');
 if(path==='/api/auth/me'&&method==='GET')return json({user:cleanUser(u),access:await accessOf(db,u)});
 if(path==='/api/auth/logout'&&method==='POST'){await run(db,'DELETE FROM sessions WHERE token=?',u.session_token);return json({ok:true},200,{'Set-Cookie':`${cookieName}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`});}
 if(path==='/api/profile'&&method==='PUT'){const b=await body(req);await run(db,'UPDATE users SET name=? WHERE id=?',text(b.name,2,120),u.id);return json({ok:true});}
 if(path==='/api/password'&&method==='PUT'){const b=await body(req);await rate(db,'password:'+u.id);if(!await bcrypt.compare(String(b.current||''),u.password))fail(400,'A senha atual está incorreta.');await db.batch([stmt(db,'UPDATE users SET password=? WHERE id=?',await bcrypt.hash(password(b.password),12),u.id),stmt(db,'DELETE FROM sessions WHERE user_id=? AND token<>?',u.id,u.session_token)]);return json({ok:true});}
 if(path==='/api/checkout/account'&&method==='POST'){const b=await body(req);await rate(db,'checkout:'+u.id,20);await salesPaused(db);if(u.role==='admin')fail(400,'Administradores já têm acesso completo.');const offer=await offerFor(db,u),items=purchaseProducts(b.products,offer,true);return json(await createCheckout(env,db,req,{email:u.email,name:u.name,userId:u.id,kind:items.includes('course')?offer.kind:'addon',items,offer}));}
 // Daqui em diante, a área do aluno exige o curso ativo; Planner e Fornitore exigem os respectivos extras.
 const access=await accessOf(db,u),need=p=>{if(!access[p].active)fail(403,lockedMessage[p],'access_'+p);};
 if(!path.startsWith('/api/admin/'))need('course');
 if(path.startsWith('/api/planner/'))need('planner');
 if(path.startsWith('/api/bookings'))need('fornitore');
 if(path==='/api/catalog'&&method==='GET'){const kinds=['track','category','module','lesson','event',...(access.planner.active?['planner']:[]),...(access.fornitore.active?['provider']:[])];const rows=(await all(db,`SELECT * FROM records WHERE kind IN (${kinds.map(()=>'?').join(',')}) AND status='published'`,...kinds)).map(readRecord);const modules=new Set(rows.filter(r=>r.kind==='module').map(r=>r.id)),files=await lessonFilesOf(db,rows.filter(r=>r.kind==='lesson').map(r=>r.id));return json({records:rows.filter(r=>r.kind!=='lesson'||modules.has(r.moduleId)).map(r=>r.kind==='lesson'?{...r,links:r.links||[],files:files[r.id]||[],plannerTasks:access.planner.active?r.plannerTasks||[]:[]}:r.kind==='track'?{...r,groups:r.groups.map(g=>[g[0],g[1].filter(id=>modules.has(id))])}:r.kind==='provider'?publicProvider(r):r.kind==='module'&&r.cardImage?{...r,cardImage:`/api/media/${r.id}?v=${r.revision}`}:r)});}
 // Material da aula para o aluno: só de aula publicada em módulo publicado (o administrador vê também rascunhos).
 if(path.startsWith('/api/files/')&&method==='GET'){const file=await first(db,"SELECT lesson_files.*,lesson.status AS lessonStatus,module.status AS moduleStatus FROM lesson_files JOIN records lesson ON lesson.id=lesson_files.lesson_id LEFT JOIN records module ON module.id=json_extract(lesson.body,'$.moduleId') WHERE lesson_files.id=?",path.split('/').pop());if(!file||(u.role!=='admin'&&(file.lessonStatus!=='published'||file.moduleStatus!=='published')))fail(404,'Arquivo não encontrado.');let data;try{data=await fs.readFile(nodePath.join(filesDir(env),file.id));}catch{fail(404,'Arquivo não encontrado.');}const download=new URL(req.url).searchParams.get('download')==='1'||!inlineTypes(file.type),fallback=file.name.replace(/[^\x20-\x7e]|["\\]/g,'_');return new Response(data,{headers:{'Content-Type':file.type,'Content-Length':String(data.length),'Content-Disposition':`${download?'attachment':'inline'}; filename="${fallback}"; filename*=UTF-8''${encodeURIComponent(file.name)}`,'Cache-Control':'private, max-age=3600','X-Content-Type-Options':'nosniff',...(download?{'Content-Security-Policy':"sandbox; default-src 'none'"}:{})}});}
 // Imagem do cartão do módulo: servida à parte (com cache) para não pesar o catálogo.
 if(path.startsWith('/api/media/')&&method==='GET'){const row=await first(db,"SELECT * FROM records WHERE id=? AND kind='module' AND status<>'archived'",path.split('/').pop());const image=row&&JSON.parse(row.body).cardImage;const match=image&&/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/.exec(image);if(!match||(row.status!=='published'&&u.role!=='admin'))fail(404,'Imagem não encontrada.');return new Response(Buffer.from(match[2],'base64'),{headers:{'Content-Type':match[1],'Cache-Control':'private, max-age=604800','X-Content-Type-Options':'nosniff'}});}
 if(path==='/api/learner'&&method==='GET')return json({data:Object.fromEntries((await all(db,'SELECT key,value FROM learner WHERE user_id=?',u.id)).map(r=>[r.key,JSON.parse(r.value)]))});
 if(path==='/api/learner'&&method==='PUT'){const b=await body(req),key=text(b.key,1,150);if(!/^(note|complete|favorite|task|active|history|planner):[a-zA-Z0-9_-]{1,100}$/.test(key))fail(400,'Registro inválido.');if(key.startsWith('planner:'))need('planner');let value=key.startsWith('note:')?text(b.value,0,20000):b.value;if(key.startsWith('planner:'))value=await validatePlanner(db,key.split(':')[1],value);else if(typeof value!=='boolean'&&typeof value!=='string'&&typeof value!=='number')fail(400,'Valor inválido.');if(JSON.stringify(value).length>(key.startsWith('planner:')?90000:21000))fail(400,'Conteúdo muito grande.');if(key.startsWith('complete:')||key.startsWith('note:')){const lesson=await first(db,"SELECT * FROM records WHERE id=? AND kind='lesson' AND status='published'",key.split(':')[1]);if(!lesson)fail(400,'Aula indisponível.');const m=JSON.parse(lesson.body).moduleId;if(!await first(db,"SELECT id FROM records WHERE id=? AND status='published'",m))fail(400,'Módulo indisponível.');}await run(db,'INSERT INTO learner(user_id,key,value,updated) VALUES(?,?,?,?) ON CONFLICT(user_id,key) DO UPDATE SET value=excluded.value,updated=excluded.updated',u.id,key,JSON.stringify(value),now());return json({ok:true});}
 if(path==='/api/planner/attachments'&&method==='GET'){const url=new URL(req.url),trackId=text(url.searchParams.get('track')||'',1,100),itemId=url.searchParams.get('item');if(itemId)await plannerTarget(db,trackId,text(itemId,1,100));else if(!await first(db,"SELECT id FROM records WHERE id=? AND kind='track' AND status='published'",trackId))fail(400,'Trilha indisponível.');const rows=await all(db,'SELECT id,track_id AS trackId,item_id AS itemId,name,type,size,created FROM planner_attachments WHERE user_id=? AND track_id=? ORDER BY created DESC',u.id,trackId);return json({attachments:rows});}
 if(path==='/api/planner/attachments'&&method==='POST'){const b=await body(req),trackId=text(b.trackId,1,100),itemId=text(b.itemId,1,100);await plannerTarget(db,trackId,itemId);const count=await first(db,'SELECT count(*) AS n FROM planner_attachments WHERE user_id=? AND track_id=? AND item_id=?',u.id,trackId,itemId);if(count.n>=5)fail(400,'Cada etapa aceita até cinco anexos.');const file=attachmentData(b.data),id=uid(),name=text(b.name,1,160);await run(db,'INSERT INTO planner_attachments(id,user_id,track_id,item_id,name,type,size,data,created) VALUES(?,?,?,?,?,?,?,?,?)',id,u.id,trackId,itemId,name,file.type,file.size,file.data,now());return json({attachment:{id,trackId,itemId,name,type:file.type,size:file.size,created:now()}});}
 if(path.startsWith('/api/planner/attachments/')&&method==='GET'){const id=path.split('/').pop(),row=await first(db,'SELECT * FROM planner_attachments WHERE id=? AND user_id=?',id,u.id);if(!row)fail(404,'Anexo não encontrado.');return attachmentResponse(row,new URL(req.url).searchParams.get('download')==='1');}
 if(path.startsWith('/api/planner/attachments/')&&method==='DELETE'){const id=path.split('/').pop(),result=await run(db,'DELETE FROM planner_attachments WHERE id=? AND user_id=?',id,u.id);if(!result.meta.changes)fail(404,'Anexo não encontrado.');return json({ok:true});}
 if(path==='/api/bookings'&&method==='GET'){const rows=await all(db,"SELECT bookings.*,records.body AS provider_body FROM bookings JOIN records ON records.id=bookings.provider_id WHERE bookings.user_id=? ORDER BY bookings.start DESC",u.id);return json({bookings:rows.map(r=>({...r,provider:JSON.parse(r.provider_body).title,provider_body:undefined}))});}
 if(path==='/api/bookings'&&method==='POST'){const b=await body(req),providerId=text(b.providerId,1,100),provider=await first(db,"SELECT * FROM records WHERE id=? AND kind='provider' AND status='published'",providerId);if(!provider)fail(400,'Prestador indisponível.');const start=Date.parse(b.start);if(!Number.isFinite(start)||start<Date.now()+3600000||start>Date.now()+31536000000)fail(400,'Escolha um horário futuro válido.');const details=JSON.parse(provider.body),conflict=await first(db,"SELECT id FROM bookings WHERE provider_id=? AND start=? AND status IN ('requested','confirmed')",providerId,new Date(start).toISOString());if(conflict)fail(409,'Este horário acabou de ser solicitado. Escolha outro.');const id=uid(),responseToken=token();await run(db,'INSERT INTO bookings(id,user_id,provider_id,start,duration,price,currency,status,payment_status,message,response_token,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',id,u.id,providerId,new Date(start).toISOString(),details.duration,details.price,details.currency,'requested','pending',text(b.message||'',0,2000),await hash(responseToken),now(),now());return json({booking:{id,status:'requested'},providerResponseLink:new URL(req.url).origin+'/app#fornitore-resposta?token='+responseToken});}
 if(path==='/api/questions'&&method==='GET'){const rows=await all(db,"SELECT * FROM records WHERE kind='question'");return json({questions:rows.map(readRecord).filter(r=>r.studentId===u.id)});}
 if(path==='/api/questions'&&method==='POST'){const b=await body(req),lessonId=text(b.lessonId,1,100);if(!await first(db,"SELECT id FROM records WHERE id=? AND kind='lesson' AND status='published'",lessonId))fail(400,'Aula indisponível.');await rate(db,'question:'+u.id,30);const id=uid();await run(db,'INSERT INTO records(id,kind,body,status,revision,updated) VALUES(?,?,?,?,1,?)',id,'question',JSON.stringify({studentId:u.id,studentName:u.name,lessonId,text:text(b.text,3,4000),answer:''}),'open',now());return json({ok:true});}
 if(!path.startsWith('/api/admin/'))fail(404,'Página não encontrada.');if(u.role!=='admin')fail(403,'Este recurso é exclusivo da administração.');
 if(path==='/api/admin/bookings'&&method==='GET'){const rows=await all(db,"SELECT bookings.*,users.name AS studentName,users.email AS studentEmail,records.body AS provider_body FROM bookings JOIN users ON users.id=bookings.user_id JOIN records ON records.id=bookings.provider_id ORDER BY bookings.created DESC");return json({bookings:rows.map(r=>({...r,provider:JSON.parse(r.provider_body).title,providerEmail:JSON.parse(r.provider_body).email,provider_body:undefined}))});}
 if(path.startsWith('/api/admin/bookings/')&&method==='PUT'){const id=path.split('/').pop(),b=await body(req),status=['requested','confirmed','declined','cancelled'].includes(b.status)?b.status:null,payment=['pending','paid','refunded','waived'].includes(b.paymentStatus)?b.paymentStatus:null;if(!status||!payment)fail(400,'Situação inválida.');const result=await run(db,'UPDATE bookings SET status=?,payment_status=?,meeting_url=?,updated=? WHERE id=?',status,payment,urlValue(b.meetingUrl||''),now(),id);if(!result.meta.changes)fail(404,'Agendamento não encontrado.');return json({ok:true});}
 if(path==='/api/admin/records'&&method==='GET')return json({records:(await all(db,'SELECT * FROM records ORDER BY updated DESC')).map(readRecord)});
 if(path==='/api/admin/records'&&method==='POST'){const b=await body(req),kind=text(b.kind,1,20),id=uid(),status=['draft','published'].includes(b.status)?b.status:'draft';if(kind==='planner'&&await first(db,"SELECT id FROM records WHERE kind='planner' AND json_extract(body,'$.trackId')=?",b.trackId))fail(409,'Esta trilha já possui um modelo de planner.');const record=await validateRecord(db,kind,b,status,id);if(kind==='category')record.order=((await first(db,"SELECT max(json_extract(body,'$.order')) AS m FROM records WHERE kind='category'"))?.m??-1)+1;await db.batch([stmt(db,'INSERT INTO records(id,kind,body,status,revision,updated) VALUES(?,?,?,?,1,?)',id,kind,JSON.stringify(record),status,now()),audit(db,u,'create',id)]);return json({id});}
 if(path.startsWith('/api/admin/records/')&&method==='PUT'){const id=path.split('/').pop(),b=await body(req),old=await first(db,'SELECT * FROM records WHERE id=?',id);if(!old)fail(404,'Conteúdo não encontrado.');if(old.kind==='question'){const content={...JSON.parse(old.body),answer:text(b.answer,1,6000)};const r=await run(db,'UPDATE records SET body=?,status=?,revision=revision+1,updated=? WHERE id=? AND revision=?',JSON.stringify(content),'answered',now(),id,b.revision);if(!r.meta.changes)fail(409,'O registro foi alterado. Atualize a página.');return json({ok:true});}if(!['draft','published','archived'].includes(b.status))fail(400,'Estado inválido.');const content=await validateRecord(db,old.kind,b,b.status,id);if(old.kind==='category')content.order=JSON.parse(old.body).order??0;const r=await run(db,'UPDATE records SET body=?,status=?,revision=revision+1,updated=? WHERE id=? AND revision=?',JSON.stringify(content),b.status,now(),id,b.revision);if(!r.meta.changes)fail(409,'Outra edição foi salva. Reabra o registro antes de tentar novamente.');await audit(db,u,'update:'+b.status,id).run();return json({ok:true});}
 if(path==='/api/admin/users'&&method==='GET'){const users=await all(db,'SELECT id,email,name,role,status,created FROM users ORDER BY created DESC');const withAccess=[];for(const x of users)withAccess.push({...cleanUser(x),access:await accessOf(db,x)});return json({users:withAccess,invites:await all(db,'SELECT email,role,kind,expires,used FROM invites WHERE expires>? ORDER BY expires DESC',now())});}
 if(/^\/api\/admin\/lessons\/[^/]+\/files$/.test(path)){const lessonId=path.split('/')[4],lesson=await first(db,"SELECT id FROM records WHERE id=? AND kind='lesson'",lessonId);if(!lesson)fail(404,'Aula não encontrada. Salve a aula antes de anexar arquivos.');
  if(method==='GET')return json({files:(await lessonFilesOf(db,[lessonId]))[lessonId]||[]});
  if(method==='POST'){let name;try{name=decodeURIComponent(req.headers.get('x-file-name')||'');}catch{fail(400,'Nome de arquivo inválido.');}name=text(name.replace(/[\\/\r\n]/g,'_'),1,160);const count=await first(db,'SELECT count(*) AS n FROM lesson_files WHERE lesson_id=?',lessonId);if(count.n>=maxLessonFiles)fail(400,`Cada aula aceita até ${maxLessonFiles} arquivos.`);const bytes=new Uint8Array(await req.arrayBuffer());if(!bytes.length)fail(400,'O arquivo está vazio.');if(bytes.length>maxLessonFile)fail(413,'Cada arquivo deve ter até 25 MB.');const type=lessonFileType(name,bytes),id=uid(),dir=filesDir(env);await fs.mkdir(dir,{recursive:true});await fs.writeFile(nodePath.join(dir,id),bytes);try{await db.batch([stmt(db,'INSERT INTO lesson_files(id,lesson_id,name,type,size,position,created) VALUES(?,?,?,?,?,?,?)',id,lessonId,name,type,bytes.length,count.n,now()),audit(db,u,'file:add',lessonId)]);}catch(e){await fs.rm(nodePath.join(dir,id),{force:true});throw e;}return json({file:{id,name,type,size:bytes.length}});}
 }
 if(path.startsWith('/api/admin/lesson-files/')&&method==='DELETE'){const id=path.split('/').pop(),file=await first(db,'SELECT * FROM lesson_files WHERE id=?',id);if(!file)fail(404,'Arquivo não encontrado.');await db.batch([stmt(db,'DELETE FROM lesson_files WHERE id=?',id),audit(db,u,'file:remove',file.lesson_id)]);await fs.rm(nodePath.join(filesDir(env),id),{force:true});return json({ok:true});}
 // Página de vendas no painel
 if(path==='/api/admin/sales-page'&&method==='GET'){const draft=await salesVersion(db,'draft'),published=await salesVersion(db,'published'),state=await salesState(db),base=published?.content||defaultContent;const history=await all(db,"SELECT v.id,v.published_at AS publishedAt,users.name AS author FROM sales_page_versions v LEFT JOIN users ON users.id=v.author_id WHERE v.status='archived' ORDER BY v.published_at DESC LIMIT 10");const publishedBy=published&&await first(db,'SELECT name FROM users WHERE id=?',published.author_id);return json({schema:salesSchema,maintenanceSchema,content:draft?.content||base,hasDraft:!!draft,draftUpdated:draft?.updated||null,changed:!!draft&&JSON.stringify(draft.content)!==JSON.stringify(base),publishedAt:published?.published_at||null,publishedBy:publishedBy?.name||null,...state,history});}
 if(path==='/api/admin/sales-page/draft'&&method==='PUT'){const b=await body(req),assets=new Set((await all(db,'SELECT id FROM site_assets')).map(r=>r.id));const content=cleanOrFail(salesSchema,b.content,assets);if(content.hero.highlight&&!content.hero.title.includes(content.hero.highlight))fail(400,'Topo da página › Palavra em destaque: ela precisa aparecer exatamente no título principal.');return json({ok:true,updated:await upsertDraft(db,content,u.id)});}
 if(path==='/api/admin/sales-page/publish'&&method==='POST'){const d=await first(db,"SELECT * FROM sales_page_versions WHERE status='draft'");if(!d)fail(400,'Não há alterações para publicar. Salve o rascunho primeiro.');const t=now();await db.batch([stmt(db,"UPDATE sales_page_versions SET status='archived',updated=? WHERE status='published'",t),stmt(db,"UPDATE sales_page_versions SET status='published',author_id=?,published_at=?,updated=? WHERE id=?",u.id,t,t,d.id),stmt(db,"DELETE FROM sales_page_versions WHERE status='archived' AND id NOT IN (SELECT id FROM sales_page_versions WHERE status='archived' ORDER BY published_at DESC LIMIT 10)"),audit(db,u,'site:publish',d.id)]);return json({ok:true,publishedAt:t});}
 if(path==='/api/admin/sales-page/discard'&&method==='POST'){await db.batch([stmt(db,"DELETE FROM sales_page_versions WHERE status='draft'"),audit(db,u,'site:discard','draft')]);return json({ok:true});}
 if(path.startsWith('/api/admin/sales-page/restore/')&&method==='POST'){const v=await first(db,"SELECT * FROM sales_page_versions WHERE id=? AND status='archived'",path.split('/').pop());if(!v)fail(404,'Versão não encontrada.');await upsertDraft(db,withDefaults(salesSchema,JSON.parse(v.content),defaultContent),u.id);await audit(db,u,'site:restore',v.id).run();return json({ok:true});}
 if(path==='/api/admin/sales-page/mode'&&method==='PUT'){const b=await body(req);if(!['published','maintenance'].includes(b.mode))fail(400,'Status inválido.');await db.batch([putSetting(db,'site.mode',b.mode),putSetting(db,'site.modeSince',String(now())),audit(db,u,'site:mode:'+b.mode,'site')]);return json({ok:true,mode:b.mode});}
 if(path==='/api/admin/sales-page/maintenance'&&method==='PUT'){const b=await body(req),content=cleanOrFail(maintenanceSchema,b.content,new Set());await db.batch([putSetting(db,'site.maintenance',JSON.stringify(content)),audit(db,u,'site:maintenance','site')]);return json({ok:true});}
 if(path==='/api/admin/site-assets'&&method==='POST'){const bytes=new Uint8Array(await req.arrayBuffer());if(!bytes.length)fail(400,'A imagem está vazia.');if(bytes.length>8*1024*1024)fail(413,'A imagem deve ter até 8 MB.');const type=bytes[0]===0xff&&bytes[1]===0xd8?'image/jpeg':bytes[0]===0x89&&bytes[1]===0x50?'image/png':String.fromCharCode(...bytes.slice(8,12))==='WEBP'?'image/webp':null;if(!type)fail(400,'Use uma imagem JPG, PNG ou WebP.');const id=uid(),dir=filesDir(env);await fs.mkdir(dir,{recursive:true});await fs.writeFile(nodePath.join(dir,'site-'+id),bytes);await run(db,'INSERT INTO site_assets(id,type,size,created) VALUES(?,?,?,?)',id,type,bytes.length,now());return json({id,url:'/media/site/'+id});}
 if(path==='/api/admin/sales'&&method==='GET'){const orders=await all(db,'SELECT orders.*,users.password IS NOT NULL AS activated FROM orders LEFT JOIN users ON users.id=orders.user_id ORDER BY orders.created DESC LIMIT 200');return json({settings:await saleSettings(db),stripe:{payments:!!env.STRIPE_SECRET_KEY,webhook:!!env.STRIPE_WEBHOOK_SECRET},orders:orders.map(o=>({...o,products:JSON.parse(o.products),activated:!!o.activated}))});}
 if(path==='/api/admin/sales/settings'&&method==='PUT'){const b=await body(req),discount=Number(b.renewalDiscount),windowDays=Number(b.renewalWindowDays);if(!Number.isInteger(discount)||discount<0||discount>90)fail(400,'O desconto de renovação deve ficar entre 0% e 90%.');if(!Number.isInteger(windowDays)||windowDays<0||windowDays>730)fail(400,'O prazo do desconto deve ficar entre 0 e 730 dias.');const values={coursePrice:reais(b.coursePrice),plannerPrice:reais(b.plannerPrice),fornitorePrice:reais(b.fornitorePrice),renewalDiscount:discount,renewalWindowDays:windowDays};await db.batch([...Object.entries(values).map(([k,v])=>stmt(db,'INSERT INTO settings(key,value,updated) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated=excluded.updated','sale.'+k,String(v),now())),audit(db,u,'sales:settings','sale')]);return json({settings:await saleSettings(db)});}
 if(path.startsWith('/api/admin/orders/')&&path.endsWith('/activation')&&method==='POST'){const id=path.split('/')[4],order=await first(db,"SELECT * FROM orders WHERE id=? AND status='paid'",id);if(!order)fail(404,'Pedido pago não encontrado.');const buyer=await first(db,'SELECT * FROM users WHERE id=?',order.user_id);if(!buyer||buyer.password)fail(409,'Esta pessoa já criou a senha. Use a recuperação de acesso se precisar.');await audit(db,u,'welcome',buyer.email).run();return json({link:await welcomeLink(db,req,buyer.email),email:buyer.email});}
 // Sequência das categorias na página inicial: recebe os ids na ordem desejada.
 if(path==='/api/admin/categories/order'&&method==='PUT'){const b=await body(req);if(!Array.isArray(b.ids)||b.ids.length>200)fail(400,'Ordem inválida.');const rows=await all(db,"SELECT * FROM records WHERE kind='category'");const byId=new Map(rows.map(r=>[r.id,r]));if(b.ids.some(id=>!byId.has(id))||new Set(b.ids).size!==b.ids.length)fail(400,'Categoria inválida na ordenação.');const t=now();await db.batch([...b.ids.map((id,i)=>stmt(db,'UPDATE records SET body=?,revision=revision+1,updated=? WHERE id=?',JSON.stringify({...JSON.parse(byId.get(id).body),order:i}),t,id)),audit(db,u,'category:order','category')]);return json({ok:true});}
 if(path==='/api/admin/entitlements'&&method==='GET'){const userId=text(new URL(req.url).searchParams.get('user')||'',1,100);return json({entitlements:await all(db,'SELECT entitlements.*,users.name AS actorName FROM entitlements LEFT JOIN users ON users.id=entitlements.reference WHERE entitlements.user_id=? ORDER BY entitlements.created DESC LIMIT 50',userId)});}
 if(path.startsWith('/api/admin/access/')&&method==='PUT'){const id=path.split('/').pop(),b=await body(req),target=await first(db,'SELECT * FROM users WHERE id=?',id);if(!target)fail(404,'Conta não encontrada.');if(target.role==='admin')fail(400,'Administradores já têm acesso completo.');const changes=await setAccess(db,id,accessSpec(b),u,'admin');return json({ok:true,changes,access:await accessOf(db,target)});}
 if(path.startsWith('/api/admin/users/')&&method==='PUT'){const id=path.split('/').pop(),b=await body(req);if(id===u.id||id==='owner')fail(400,'A conta proprietária e sua própria permissão não podem ser alteradas aqui.');if(!['admin','student'].includes(b.role)||!['active','suspended'].includes(b.status))fail(400,'Perfil inválido.');if(!await first(db,'SELECT id FROM users WHERE id=?',id))fail(404,'Conta não encontrada.');await db.batch([stmt(db,'UPDATE users SET role=?,status=? WHERE id=?',b.role,b.status,id),stmt(db,'DELETE FROM sessions WHERE user_id=?',id),audit(db,u,'user:'+b.role+':'+b.status,id)]);return json({ok:true});}
 if(path==='/api/admin/invites'&&method==='POST'){const b=await body(req),mail=email(b.email),kind=b.kind==='reset'?'reset':'invite',role=b.role==='admin'?'admin':'student';const existing=await first(db,'SELECT * FROM users WHERE email=?',mail);if(kind==='invite'&&existing)fail(409,'Este e-mail já tem uma conta.');if(kind==='reset'&&!existing)fail(404,'Conta não encontrada.');const grants=kind==='invite'&&role==='student'&&b.access?.courseExpires?accessSpec(b.access):null;if(grants&&grants.courseExpires<now()+2*86400)fail(400,'Para convites, a validade do acesso deve ser de pelo menos dois dias.');const raw=token(),expires=now()+86400;await db.batch([stmt(db,'UPDATE invites SET used=1 WHERE email=?',mail),stmt(db,'INSERT INTO invites(token,email,role,kind,expires,used,grants) VALUES(?,?,?,?,?,0,?)',await hash(raw),mail,existing?.role||role,kind,expires,grants?JSON.stringify(grants):null),audit(db,u,kind,mail)]);return json({token:raw,expires,email:mail});}
 if(path==='/api/admin/audit'&&method==='GET')return json({entries:await all(db,'SELECT audit.*,users.name AS actorName FROM audit LEFT JOIN users ON users.id=audit.actor ORDER BY audit.created DESC LIMIT 100')});
 fail(404,'Recurso não encontrado.');
}
const pageHeaders=type=>({'Content-Type':type,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data: https:; frame-src https://www.youtube-nocookie.com https://player.vimeo.com; media-src 'self' https:; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"});
const htmlPage=(req,html,status=200,extra={})=>new Response(req.method==='HEAD'?null:html,{status,headers:{...pageHeaders('text/html; charset=utf-8'),...extra}});
// Página de vendas, termos, privacidade e imagens do site: geradas a partir do conteúdo publicado no painel.
async function sitePage(req,env,path){
 const db=env.DB,url=new URL(req.url),viewer=db?await session(req,db):null,isAdmin=viewer?.role==='admin';
 if(path.startsWith('/media/site/')){
  const id=path.split('/').pop(),asset=db&&/^[0-9a-f-]{36}$/.test(id)&&await first(db,'SELECT * FROM site_assets WHERE id=?',id);if(!asset)return new Response('Not found',{status:404});
  const isPublic=!!(await first(db,"SELECT 1 AS x FROM sales_page_versions WHERE status='published' AND instr(content,?)>0",id));if(!isPublic&&!isAdmin)return new Response('Not found',{status:404});
  let data;try{data=await fs.readFile(nodePath.join(filesDir(env),'site-'+id));}catch{return new Response('Not found',{status:404});}
  return new Response(req.method==='HEAD'?null:data,{headers:{'Content-Type':asset.type,'Cache-Control':isPublic?'public, max-age=86400':'private, no-store','X-Content-Type-Options':'nosniff'}});
 }
 const published=db?await salesVersion(db,'published'):null,content=published?.content||structuredClone(defaultContent),state=db?await salesState(db):{mode:'published',maintenance:defaultMaintenance};
 const preview=isAdmin?url.searchParams.get('preview'):null,draft=preview==='rascunho'?(await salesVersion(db,'draft'))?.content||content:null;
 if(path==='/'){
  if(draft)return htmlPage(req,renderSalesPage(draft,{banner:adminBanner('draft')}));
  if(preview==='manutencao')return htmlPage(req,renderMaintenance(state.maintenance,{banner:adminBanner('maintenance-preview')}));
  if(state.mode==='maintenance')return isAdmin?htmlPage(req,renderSalesPage(content,{banner:adminBanner('maintenance')})):htmlPage(req,renderMaintenance(state.maintenance),503,{'Retry-After':'3600'});
  return htmlPage(req,renderSalesPage(content));
 }
 return htmlPage(req,renderLegal(draft||content,path.slice(1),{banner:draft?adminBanner('draft'):''}));
}
export default{async fetch(req,env){const path=new URL(req.url).pathname;try{if(path.startsWith('/api/'))return await api(req,env,path);if(!['GET','HEAD'].includes(req.method))return new Response('Method not allowed',{status:405});if(['/','/termos','/privacidade'].includes(path)||path.startsWith('/media/site/'))return await sitePage(req,env,path);const asset=env.asset?.(path)||(!path.includes('.')&&env.asset?.(path+'.html'));if(!asset)return new Response('Not found',{status:404});return new Response(req.method==='HEAD'?null:asset.body,{headers:pageHeaders(asset.type)});}catch(e){if(!e.status)console.error('Request failed',path,e.message,e.cause?.code||e.cause?.message||'');return json({error:e.status?e.message:'Não foi possível concluir. Seus dados permanecem no formulário; tente novamente.',...(e.code?{code:e.code}:{})},e.status||503);}}};
