import bcrypt from 'bcryptjs';
import seed from './seed.json';
import assets from './assets.generated.js';

const cookieName='__Host-partiu';
const now=()=>Math.floor(Date.now()/1000);
const uid=()=>crypto.randomUUID();
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new HttpError(status,message);};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff',...headers}});
const stmt=(db,sql,...args)=>db.prepare(sql).bind(...args);
const run=(db,sql,...args)=>stmt(db,sql,...args).run();
const first=(db,sql,...args)=>stmt(db,sql,...args).first();
const all=async(db,sql,...args)=>(await stmt(db,sql,...args).all()).results;
const text=(v,min=0,max=500)=>{if(typeof v!=='string'||v.trim().length<min||v.length>max)fail(400,`Preencha os campos corretamente (até ${max} caracteres).`);return v.trim();};
const email=v=>{v=text(v,3,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))fail(400,'Informe um e-mail válido.');return v;};
const password=v=>{if(typeof v!=='string'||v.length<12||bcrypt.truncates(v))fail(400,'Use uma senha com pelo menos 12 caracteres e no máximo 72 bytes.');return v;};
const cleanUser=u=>({id:u.id,email:u.email,name:u.name,role:u.role,status:u.status,created:u.created});
const audit=(db,u,action,target)=>stmt(db,'INSERT INTO audit(id,actor,action,target,created) VALUES(?,?,?,?,?)',uid(),u.id,action,target,now());
const readRecord=r=>({...JSON.parse(r.body),id:r.id,kind:r.kind,status:r.status,revision:r.revision,updated:r.updated});
function urlValue(v){if(!v)return '';let u;try{u=new URL(v);}catch{fail(400,'Informe um endereço HTTPS válido.');}if(u.protocol!=='https:'||u.username||u.password)fail(400,'Use um endereço HTTPS sem credenciais.');return u.href;}
export function videoSource(value){const s=urlValue(value);if(!s)return null;const u=new URL(s),host=u.hostname.toLowerCase();if(['www.youtube.com','youtube.com','youtu.be','www.youtube-nocookie.com'].includes(host)){const id=host==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').pop();if(!/^[a-zA-Z0-9_-]{11}$/.test(id))fail(400,'Link do YouTube inválido.');return{type:'iframe',url:'https://www.youtube-nocookie.com/embed/'+id};}if(['vimeo.com','www.vimeo.com','player.vimeo.com'].includes(host)){const id=u.pathname.split('/').filter(Boolean).pop();if(!/^\d+$/.test(id))fail(400,'Link do Vimeo inválido.');return{type:'iframe',url:'https://player.vimeo.com/video/'+id};}if(/\.mp4$/i.test(u.pathname))return{type:'video',url:s};fail(400,'Use um vídeo do YouTube, Vimeo ou um arquivo MP4 em HTTPS.');}
async function body(req){const raw=await req.text();if(raw.length>100000)fail(413,'Conteúdo muito grande.');try{return JSON.parse(raw);}catch{fail(400,'Dados inválidos.');}}
async function rate(db,key,max=12){const t=now();const row=await stmt(db,'INSERT INTO limits(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN until<? THEN 1 ELSE count+1 END,until=CASE WHEN until<? THEN excluded.until ELSE until END RETURNING count',key,t+900,t,t).first();if(row.count>max)fail(429,'Muitas tentativas. Aguarde 15 minutos e tente novamente.');}
async function session(req,db){const raw=req.headers.get('cookie')||'';const value=raw.split(';').map(s=>s.trim()).find(s=>s.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(!value||!/^[a-f0-9]{64}$/.test(value))return null;return first(db,'SELECT users.*,sessions.token AS session_token FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token=? AND sessions.expires>? AND users.status=?',await hash(value),now(),'active');}
async function loginResponse(db,u){const value=token();await db.batch([stmt(db,'DELETE FROM sessions WHERE expires<?',now()),stmt(db,'INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)',await hash(value),u.id,now()+86400)]);return json({user:cleanUser(u)},200,{'Set-Cookie':`${cookieName}=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=86400`});}
async function initializeCatalog(db,u){const statements=seed.map(r=>stmt(db,'INSERT OR IGNORE INTO records(id,kind,body,status,revision,updated) VALUES(?,?,?,?,1,?)',r.id,r.kind,JSON.stringify(r.body),r.status,now()));for(let i=0;i<statements.length;i+=30)await db.batch(statements.slice(i,i+30));}
async function validateRecord(db,kind,b,status,id){const base={title:text(b.title,1,160),description:text(b.description||'',0,10000),order:Number.isInteger(Number(b.order))?Number(b.order):0};if(base.order<0||base.order>10000)fail(400,'Ordem inválida.');if(kind==='module')return{...base,category:text(b.category||'CURSOS',1,80),symbol:text(b.symbol||'◇',1,8)};
 if(kind==='lesson'){const moduleId=text(b.moduleId,1,100);const m=await first(db,'SELECT id FROM records WHERE id=? AND kind=? AND status<>?',moduleId,'module','archived');if(!m)fail(400,'Selecione um módulo ativo.');const video=videoSource(b.videoUrl||'');if(status==='published'&&!video)fail(400,'Insira o vídeo antes de publicar a aula.');const tasks=Array.isArray(b.tasks)?b.tasks.map(t=>({id:text(t.id||uid(),1,100),title:text(t.title,1,300)})):[];if(tasks.length>30||new Set(tasks.map(t=>t.id)).size!==tasks.length)fail(400,'Tarefas inválidas.');return{...base,moduleId,videoUrl:urlValue(b.videoUrl||''),video,duration:Math.max(0,Math.min(999,Number(b.duration)||0)),tasks};}
 if(kind==='track'){if(!Array.isArray(b.groups)||b.groups.length>25)fail(400,'Organize as etapas da trilha.');const groups=[];for(const g of b.groups){if(!Array.isArray(g)||!Array.isArray(g[1])||g[1].length>30)fail(400,'Etapa inválida.');const ids=[...new Set(g[1])];for(const mid of ids){if(typeof mid!=='string'||!await first(db,'SELECT id FROM records WHERE id=? AND kind=? AND status<>?',mid,'module','archived'))fail(400,'A etapa contém um módulo indisponível.');}groups.push([text(g[0],1,160),ids]);}if(status==='published'&&(!groups.length||!groups.some(g=>g[1].length)))fail(400,'Adicione módulos antes de publicar a trilha.');return{...base,name:base.title,tag:text(b.tag||'SUA JORNADA',0,100),groups};}
 if(kind==='event'){const start=Date.parse(b.start),end=Date.parse(b.end);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)fail(400,'Informe início e término válidos.');return{...base,start:new Date(start).toISOString(),end:new Date(end).toISOString(),host:text(b.host||'',0,160),location:text(b.location||'',0,300),joinUrl:urlValue(b.joinUrl||'')};}fail(400,'Tipo de conteúdo inválido.');}

async function api(req,env,path){const db=env.DB;if(!db)fail(503,'O armazenamento está indisponível. Tente novamente.');const method=req.method;
 if(!['GET','HEAD'].includes(method)){if(req.headers.get('Origin')!==new URL(req.url).origin||req.headers.get('X-Partiu-Request')!=='1')fail(403,'Solicitação não autorizada. Atualize a página.');if(!req.headers.get('content-type')?.startsWith('application/json'))fail(415,'Use dados JSON.');}
 if(path==='/api/auth/status'){const count=await first(db,'SELECT count(*) AS n FROM users');const owner=req.headers.get('oai-authenticated-user-email')?.toLowerCase();return json({setup:count.n===0&&!!env.OWNER_EMAIL&&owner===env.OWNER_EMAIL.toLowerCase()});}
 if(path==='/api/auth/setup'&&method==='POST'){if(!env.OWNER_EMAIL||req.headers.get('oai-authenticated-user-email')?.toLowerCase()!==env.OWNER_EMAIL.toLowerCase())fail(403,'A configuração inicial está disponível somente ao proprietário.');const b=await body(req),name=text(b.name,2,120),pw=password(b.password),mail=env.OWNER_EMAIL.toLowerCase();const u={id:'owner',email:mail,name,password:await bcrypt.hash(pw,12),role:'admin',status:'active',created:now()};const r=await run(db,'INSERT INTO users(id,email,name,password,role,status,created) SELECT ?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM users)',u.id,u.email,u.name,u.password,u.role,u.status,u.created);if(!r.meta.changes)fail(409,'A conta administradora já foi configurada. Entre com sua senha.');await initializeCatalog(db,u);return loginResponse(db,u);}
 if(path==='/api/auth/login'&&method==='POST'){const b=await body(req),mail=email(b.email);await rate(db,'login:'+await hash(mail));await rate(db,'ip:'+await hash(req.headers.get('cf-connecting-ip')||'unknown'),60);const u=await first(db,'SELECT * FROM users WHERE email=?',mail);const pw=typeof b.password==='string'&&b.password.length<=200?b.password:'';const valid=await bcrypt.compare(pw,u?.password||'$2b$12$C6UzMDM.H6dfI/f/IKcEe.5SX2x4lqReGVSjtZKfX9NbTXMC63eEq');if(!u||!valid||u.status!=='active')fail(401,'E-mail ou senha inválidos, ou acesso suspenso.');return loginResponse(db,u);}
 if(path==='/api/auth/activate'&&method==='POST'){const b=await body(req);await rate(db,'activate:'+await hash(req.headers.get('cf-connecting-ip')||'unknown'),30);const t=text(b.token,64,64),name=text(b.name,2,120),pw=password(b.password);const inv=await first(db,'SELECT * FROM invites WHERE token=? AND used=0 AND expires>?',await hash(t),now());if(!inv)fail(400,'Este link expirou ou já foi utilizado. Solicite um novo ao administrador.');const stored=await bcrypt.hash(pw,12);const existing=await first(db,'SELECT * FROM users WHERE email=?',inv.email);if(inv.kind==='reset'&&!existing)fail(400,'Conta não encontrada.');if(inv.kind==='invite'&&existing)fail(409,'Esta conta já existe. Use a recuperação de acesso.');const used=await run(db,'UPDATE invites SET used=1 WHERE token=? AND used=0 AND expires>?',inv.token,now());if(!used.meta.changes)fail(409,'Link já utilizado.');const id=existing?.id||uid();await db.batch([inv.kind==='reset'?stmt(db,'UPDATE users SET password=? WHERE id=?',stored,id):stmt(db,'INSERT INTO users(id,email,name,password,role,status,created) VALUES(?,?,?,?,?,?,?)',id,inv.email,name,stored,inv.role,'active',now()),stmt(db,'DELETE FROM sessions WHERE user_id=?',id)]);return json({ok:true,message:'Senha definida. Entre com seu e-mail.'});}
 const u=await session(req,db);if(!u)fail(401,'Entre na sua conta para continuar.');
 if(path==='/api/auth/me'&&method==='GET')return json({user:cleanUser(u)});
 if(path==='/api/auth/logout'&&method==='POST'){await run(db,'DELETE FROM sessions WHERE token=?',u.session_token);return json({ok:true},200,{'Set-Cookie':`${cookieName}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`});}
 if(path==='/api/profile'&&method==='PUT'){const b=await body(req);await run(db,'UPDATE users SET name=? WHERE id=?',text(b.name,2,120),u.id);return json({ok:true});}
 if(path==='/api/password'&&method==='PUT'){const b=await body(req);await rate(db,'password:'+u.id);if(!await bcrypt.compare(String(b.current||''),u.password))fail(400,'A senha atual está incorreta.');await db.batch([stmt(db,'UPDATE users SET password=? WHERE id=?',await bcrypt.hash(password(b.password),12),u.id),stmt(db,'DELETE FROM sessions WHERE user_id=? AND token<>?',u.id,u.session_token)]);return json({ok:true});}
 if(path==='/api/catalog'&&method==='GET'){const rows=(await all(db,"SELECT * FROM records WHERE kind IN ('track','module','lesson','event') AND status='published'")).map(readRecord);const modules=new Set(rows.filter(r=>r.kind==='module').map(r=>r.id));return json({records:rows.filter(r=>r.kind!=='lesson'||modules.has(r.moduleId)).map(r=>r.kind==='track'?{...r,groups:r.groups.map(g=>[g[0],g[1].filter(id=>modules.has(id))])}:r)});}
 if(path==='/api/learner'&&method==='GET')return json({data:Object.fromEntries((await all(db,'SELECT key,value FROM learner WHERE user_id=?',u.id)).map(r=>[r.key,JSON.parse(r.value)]))});
 if(path==='/api/learner'&&method==='PUT'){const b=await body(req),key=text(b.key,1,150);if(!/^(note|complete|favorite|task|active|history):[a-zA-Z0-9_-]{1,100}$/.test(key))fail(400,'Registro inválido.');const value=key.startsWith('note:')?text(b.value,0,20000):b.value;if(!key.startsWith('note:')&&typeof value!=='boolean'&&typeof value!=='string'&&typeof value!=='number')fail(400,'Valor inválido.');if(JSON.stringify(value).length>21000)fail(400,'Conteúdo muito grande.');if(key.startsWith('complete:')||key.startsWith('note:')){const lesson=await first(db,"SELECT * FROM records WHERE id=? AND kind='lesson' AND status='published'",key.split(':')[1]);if(!lesson)fail(400,'Aula indisponível.');const m=JSON.parse(lesson.body).moduleId;if(!await first(db,"SELECT id FROM records WHERE id=? AND status='published'",m))fail(400,'Módulo indisponível.');}await run(db,'INSERT INTO learner(user_id,key,value,updated) VALUES(?,?,?,?) ON CONFLICT(user_id,key) DO UPDATE SET value=excluded.value,updated=excluded.updated',u.id,key,JSON.stringify(value),now());return json({ok:true});}
 if(path==='/api/questions'&&method==='GET'){const rows=await all(db,"SELECT * FROM records WHERE kind='question'");return json({questions:rows.map(readRecord).filter(r=>r.studentId===u.id)});}
 if(path==='/api/questions'&&method==='POST'){const b=await body(req),lessonId=text(b.lessonId,1,100);if(!await first(db,"SELECT id FROM records WHERE id=? AND kind='lesson' AND status='published'",lessonId))fail(400,'Aula indisponível.');await rate(db,'question:'+u.id,30);const id=uid();await run(db,'INSERT INTO records(id,kind,body,status,revision,updated) VALUES(?,?,?,?,1,?)',id,'question',JSON.stringify({studentId:u.id,studentName:u.name,lessonId,text:text(b.text,3,4000),answer:''}),'open',now());return json({ok:true});}
 if(!path.startsWith('/api/admin/'))fail(404,'Página não encontrada.');if(u.role!=='admin')fail(403,'Este recurso é exclusivo da administração.');
 if(path==='/api/admin/records'&&method==='GET')return json({records:(await all(db,'SELECT * FROM records ORDER BY updated DESC')).map(readRecord)});
 if(path==='/api/admin/records'&&method==='POST'){const b=await body(req),kind=text(b.kind,1,20),id=uid(),status=['draft','published'].includes(b.status)?b.status:'draft';const record=await validateRecord(db,kind,b,status,id);await db.batch([stmt(db,'INSERT INTO records(id,kind,body,status,revision,updated) VALUES(?,?,?,?,1,?)',id,kind,JSON.stringify(record),status,now()),audit(db,u,'create',id)]);return json({id});}
 if(path.startsWith('/api/admin/records/')&&method==='PUT'){const id=path.split('/').pop(),b=await body(req),old=await first(db,'SELECT * FROM records WHERE id=?',id);if(!old)fail(404,'Conteúdo não encontrado.');if(old.kind==='question'){const content={...JSON.parse(old.body),answer:text(b.answer,1,6000)};const r=await run(db,'UPDATE records SET body=?,status=?,revision=revision+1,updated=? WHERE id=? AND revision=?',JSON.stringify(content),'answered',now(),id,b.revision);if(!r.meta.changes)fail(409,'O registro foi alterado. Atualize a página.');return json({ok:true});}if(!['draft','published','archived'].includes(b.status))fail(400,'Estado inválido.');const content=await validateRecord(db,old.kind,b,b.status,id);const r=await run(db,'UPDATE records SET body=?,status=?,revision=revision+1,updated=? WHERE id=? AND revision=?',JSON.stringify(content),b.status,now(),id,b.revision);if(!r.meta.changes)fail(409,'Outra edição foi salva. Reabra o registro antes de tentar novamente.');await audit(db,u,'update:'+b.status,id).run();return json({ok:true});}
 if(path==='/api/admin/users'&&method==='GET'){const users=(await all(db,'SELECT id,email,name,role,status,created FROM users ORDER BY created DESC')).map(cleanUser);return json({users,invites:await all(db,'SELECT email,role,kind,expires,used FROM invites WHERE expires>? ORDER BY expires DESC',now())});}
 if(path.startsWith('/api/admin/users/')&&method==='PUT'){const id=path.split('/').pop(),b=await body(req);if(id===u.id||id==='owner')fail(400,'A conta proprietária e sua própria permissão não podem ser alteradas aqui.');if(!['admin','student'].includes(b.role)||!['active','suspended'].includes(b.status))fail(400,'Perfil inválido.');if(!await first(db,'SELECT id FROM users WHERE id=?',id))fail(404,'Conta não encontrada.');await db.batch([stmt(db,'UPDATE users SET role=?,status=? WHERE id=?',b.role,b.status,id),stmt(db,'DELETE FROM sessions WHERE user_id=?',id),audit(db,u,'user:'+b.role+':'+b.status,id)]);return json({ok:true});}
 if(path==='/api/admin/invites'&&method==='POST'){const b=await body(req),mail=email(b.email),kind=b.kind==='reset'?'reset':'invite',role=b.role==='admin'?'admin':'student';const existing=await first(db,'SELECT * FROM users WHERE email=?',mail);if(kind==='invite'&&existing)fail(409,'Este e-mail já tem uma conta.');if(kind==='reset'&&!existing)fail(404,'Conta não encontrada.');const raw=token(),expires=now()+86400;await db.batch([stmt(db,'UPDATE invites SET used=1 WHERE email=?',mail),stmt(db,'INSERT INTO invites(token,email,role,kind,expires,used) VALUES(?,?,?,?,?,0)',await hash(raw),mail,existing?.role||role,kind,expires),audit(db,u,kind,mail)]);return json({token:raw,expires,email:mail});}
 if(path==='/api/admin/audit'&&method==='GET')return json({entries:await all(db,'SELECT audit.*,users.name AS actorName FROM audit LEFT JOIN users ON users.id=audit.actor ORDER BY audit.created DESC LIMIT 100')});
 fail(404,'Recurso não encontrado.');
}
export default{async fetch(req,env){const path=new URL(req.url).pathname;try{if(path.startsWith('/api/'))return await api(req,env,path);if(!['GET','HEAD'].includes(req.method))return new Response('Method not allowed',{status:405});const asset=assets[path==='/'?'/index.html':path];if(!asset)return new Response('Not found',{status:404});return new Response(req.method==='HEAD'?null:asset.body,{headers:{'Content-Type':asset.type,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data: https:; frame-src https://www.youtube-nocookie.com https://player.vimeo.com; media-src https:; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com"}});}catch(e){if(!e.status)console.error('Request failed',path,e.message);return json({error:e.status?e.message:'Não foi possível concluir. Seus dados permanecem no formulário; tente novamente.'},e.status||503);}}};
