import bcrypt from 'bcryptjs';
import seed from './seed.json';
import assets from './assets.generated.js';

const cookieName='__Host-arrivo';
const now=()=>Math.floor(Date.now()/1000);
const uid=()=>crypto.randomUUID();
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new HttpError(status,message);};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff',...headers}});
const stmt=(db,sql,...args)=>db.prepare(sql).bind(...args);
const run=(db,sql,...args)=>stmt(db,sql,...args).run();
const first=(db,sql,...args)=>stmt(db,sql,...args).first();
const all=async(db,sql,...args)=>(await stmt(db,sql,...args).all()).results;
const text=(v,min=0,max=500)=>{if(typeof v!=='string'||v.trim().length<min||v.length>max)fail(400,`Preencha os campos corretamente (até ${max} caracteres).`);return v.trim();};
const email=v=>{v=text(v,3,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))fail(400,'Informe um e-mail válido.');return v;};
const password=v=>{if(typeof v!=='string'||v.length<12||bcrypt.truncates(v))fail(400,'Use uma senha com pelo menos 12 caracteres e no máximo 72 bytes.');return v;};
const cleanUser=u=>({id:u.id,email:u.email,name:u.name,role:u.role,status:u.status,created:u.created});
const audit=(db,u,action,target)=>stmt(db,'INSERT INTO audit(id,actor,action,target,created) VALUES(?,?,?,?,?)',uid(),u.id,action,target,now());
const readRecord=r=>({...JSON.parse(r.body),id:r.id,kind:r.kind,status:r.status,revision:r.revision,updated:r.updated});
function urlValue(v){if(!v)return '';let u;try{u=new URL(v);}catch{fail(400,'Informe um endereço HTTPS válido.');}if(u.protocol!=='https:'||u.username||u.password)fail(400,'Use um endereço HTTPS sem credenciais.');return u.href;}
export function videoSource(value){const s=urlValue(value);if(!s)return null;const u=new URL(s),host=u.hostname.toLowerCase();if(['www.youtube.com','youtube.com','youtu.be','www.youtube-nocookie.com'].includes(host)){const id=host==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').pop();if(!/^[a-zA-Z0-9_-]{11}$/.test(id))fail(400,'Link do YouTube inválido.');return{type:'iframe',url:'https://www.youtube-nocookie.com/embed/'+id};}if(['vimeo.com','www.vimeo.com','player.vimeo.com'].includes(host)){const id=u.pathname.split('/').filter(Boolean).pop();if(!/^\d+$/.test(id))fail(400,'Link do Vimeo inválido.');return{type:'iframe',url:'https://player.vimeo.com/video/'+id};}if(/\.mp4$/i.test(u.pathname))return{type:'video',url:s};fail(400,'Use um vídeo do YouTube, Vimeo ou um arquivo MP4 em HTTPS.');}
async function body(req){const raw=await req.text(),path=new URL(req.url).pathname,limit=path.startsWith('/api/planner/attachments')?2900000:path.startsWith('/api/admin/records')?850000:100000;if(raw.length>limit)fail(413,'Conteúdo muito grande.');try{return JSON.parse(raw);}catch{fail(400,'Dados inválidos.');}}
async function rate(db,key,max=12){const t=now();const row=await stmt(db,'INSERT INTO limits(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN until<? THEN 1 ELSE count+1 END,until=CASE WHEN until<? THEN excluded.until ELSE until END RETURNING count',key,t+900,t,t).first();if(row.count>max)fail(429,'Muitas tentativas. Aguarde 15 minutos e tente novamente.');}
async function session(req,db){const raw=req.headers.get('cookie')||'';const value=raw.split(';').map(s=>s.trim()).find(s=>s.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(!value||!/^[a-f0-9]{64}$/.test(value))return null;return first(db,'SELECT users.*,sessions.token AS session_token FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token=? AND sessions.expires>? AND users.status=?',await hash(value),now(),'active');}
async function loginResponse(db,u){const value=token();await db.batch([stmt(db,'DELETE FROM sessions WHERE expires<?',now()),stmt(db,'INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)',await hash(value),u.id,now()+86400)]);return json({user:cleanUser(u)},200,{'Set-Cookie':`${cookieName}=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=86400`});}
async function initializeCatalog(db,u){const statements=seed.map(r=>stmt(db,'INSERT OR IGNORE INTO records(id,kind,body,status,revision,updated) VALUES(?,?,?,?,1,?)',r.id,r.kind,JSON.stringify(r.body),r.status,now()));for(let i=0;i<statements.length;i+=30)await db.batch(statements.slice(i,i+30));}
function validateTrackImage(value){
 if(value===undefined||value==='')return '';
 if(typeof value!=='string'||value.length>683000)fail(400,'A imagem deve ter até 500 KB.');
 const match=/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/]+={0,2})$/.exec(value);
 if(!match)fail(400,'Use uma imagem JPG, PNG ou WebP.');
 let bytes;try{bytes=atob(match[2]);}catch{fail(400,'Imagem inválida.');}
 if(bytes.length>512000)fail(400,'A imagem deve ter até 500 KB.');
 const valid=match[1]==='png'?bytes.startsWith('\x89PNG\r\n\x1a\n'):match[1]==='jpeg'?bytes.startsWith('\xff\xd8\xff'):bytes.startsWith('RIFF')&&bytes.slice(8,12)==='WEBP';
 if(!valid)fail(400,'Arquivo de imagem inválido.');return value;
}


async function plannerTarget(db,trackId,itemId){const row=await first(db,"SELECT * FROM records WHERE id=? AND kind='track' AND status='published'",trackId);if(!row)fail(400,'Trilha indisponível.');const track=JSON.parse(row.body);if(!track.groups.flatMap(g=>g[1]).includes(itemId))fail(400,'Etapa indisponível.');return row;}
function attachmentData(value){if(typeof value!=='string'||value.length>2800000)fail(400,'O arquivo deve ter até 2 MB.');const match=/^data:(application\/pdf|image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/]+={0,2})$/.exec(value);if(!match)fail(400,'Envie um arquivo PDF, JPG, PNG ou WebP.');let bytes;try{bytes=atob(match[2]);}catch{fail(400,'Arquivo inválido.');}if(bytes.length>2097152)fail(400,'O arquivo deve ter até 2 MB.');const valid=match[1]==='application/pdf'?bytes.startsWith('%PDF-'):match[1]==='image/png'?bytes.startsWith('\x89PNG\r\n\x1a\n'):match[1]==='image/jpeg'?bytes.startsWith('\xff\xd8\xff'):bytes.startsWith('RIFF')&&bytes.slice(8,12)==='WEBP';if(!valid)fail(400,'O conteúdo do arquivo não corresponde ao formato informado.');return{type:match[1],data:match[2],size:bytes.length};}
function attachmentResponse(row,download=false){const binary=atob(row.data),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const fallback=row.type==='application/pdf'?'documento.pdf':row.type==='image/png'?'imagem.png':row.type==='image/webp'?'imagem.webp':'imagem.jpg',name=(row.name||fallback).replace(/[\r\n"\\/]/g,'_');return new Response(bytes,{headers:{'Content-Type':row.type,'Content-Length':String(row.size),'Content-Disposition':`${download?'attachment':'inline'}; filename="${name}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
async function validatePlanner(db,trackId,value){

 const row=await first(db,"SELECT * FROM records WHERE id=? AND kind='track' AND status='published'",trackId);if(!row)fail(400,'Trilha indisponível.');
 if(!value||typeof value!=='object'||Array.isArray(value)||!Array.isArray(value.items)||value.items.length>100)fail(400,'Planner inválido.');
 const track=JSON.parse(row.body),allowed=new Set(track.groups.flatMap(g=>g[1]));if(value.items.length!==new Set(value.items.map(i=>i.id)).size)fail(400,'Etapas duplicadas.');
 const statuses=new Set(['not_started','organizing','waiting','in_progress','blocked','done']),priorities=new Set(['low','normal','high']),currencies=new Set(['EUR','BRL']);
 const clean=[];for(const item of value.items){const id=text(item.id,1,100);if(!allowed.has(id))fail(400,'Etapa indisponível.');const status=statuses.has(item.status)?item.status:'not_started',priority=priorities.has(item.priority)?item.priority:'normal',currency=currencies.has(item.currency)?item.currency:'EUR';const dateValue=v=>{if(!v)return '';if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v)))fail(400,'Data inválida.');return v;};const cost=item.cost===''?'':Number(item.cost);if(cost!==''&&(!Number.isFinite(cost)||cost<0||cost>9999999))fail(400,'Custo inválido.');clean.push({id,title:text(item.title||'',0,160),phase:text(item.phase||'',0,160),status,responsible:text(item.responsible||'',0,120),issuanceDate:dateValue(item.issuanceDate),dueDate:dateValue(item.dueDate),cost,currency,priority,documentNumber:text(item.documentNumber||'',0,120),location:text(item.location||'',0,160),attachmentName:text(item.attachmentName||'',0,160),attachmentUrl:urlValue(item.attachmentUrl||''),notes:text(item.notes||'',0,5000),updated:Number.isFinite(Number(item.updated))?Number(item.updated):now()*1000});}
 return{trackId,items:clean,updated:now()*1000};
}
async function validateRecord(db,kind,b,status,id){const base={title:text(b.title,1,160),description:text(b.description||'',0,10000),order:Number.isInteger(Number(b.order))?Number(b.order):0};if(base.order<0||base.order>10000)fail(400,'Ordem inválida.');if(kind==='module')return{...base,category:text(b.category||'CURSOS',1,80),symbol:text(b.symbol||'◇',1,8)};
 if(kind==='lesson'){const moduleId=text(b.moduleId,1,100);const m=await first(db,'SELECT id FROM records WHERE id=? AND kind=? AND status<>?',moduleId,'module','archived');if(!m)fail(400,'Selecione um módulo ativo.');const video=videoSource(b.videoUrl||'');if(status==='published'&&!video)fail(400,'Insira o vídeo antes de publicar a aula.');const tasks=Array.isArray(b.tasks)?b.tasks.map(t=>({id:text(t.id||uid(),1,100),title:text(t.title,1,300)})):[];if(tasks.length>30||new Set(tasks.map(t=>t.id)).size!==tasks.length)fail(400,'Tarefas inválidas.');return{...base,moduleId,videoUrl:urlValue(b.videoUrl||''),video,duration:Math.max(0,Math.min(999,Number(b.duration)||0)),tasks};}
 if(kind==='track'){if(!Array.isArray(b.groups)||b.groups.length>25)fail(400,'Organize as etapas da trilha.');const groups=[];for(const g of b.groups){if(!Array.isArray(g)||!Array.isArray(g[1])||g[1].length>30)fail(400,'Etapa inválida.');const ids=[...new Set(g[1])];for(const mid of ids){if(typeof mid!=='string'||!await first(db,'SELECT id FROM records WHERE id=? AND kind=? AND status<>?',mid,'module','archived'))fail(400,'A etapa contém um módulo indisponível.');}groups.push([text(g[0],1,160),ids]);}if(status==='published'&&(!groups.length||!groups.some(g=>g[1].length)))fail(400,'Adicione módulos antes de publicar a trilha.');return{...base,backgroundImage:validateTrackImage(b.backgroundImage),name:base.title,tag:text(b.tag||'SUA JORNADA',0,100),groups};}
 if(kind==='provider'){const price=Number(b.price),duration=Number(b.duration);if(!Number.isFinite(price)||price<0||price>9999999)fail(400,'Preço inválido.');if(!Number.isInteger(duration)||duration<15||duration>480)fail(400,'Duração inválida.');return{...base,name:base.title,brand:text(b.brand||'',0,120),specialty:text(b.specialty,2,120),services:text(b.services||'',0,2000),summary:text(b.summary||'',0,500),bio:text(b.bio||'',0,10000),photo:validateTrackImage(b.photo),price,currency:b.currency==='BRL'?'BRL':'EUR',duration,rating:Math.max(0,Math.min(5,Number(b.rating)||0)),reviewCount:Math.max(0,Math.min(999999,Number(b.reviewCount)||0)),city:text(b.city||'',0,120),languages:text(b.languages||'',0,300),email:email(b.email),phone:text(b.phone||'',0,60),website:urlValue(b.website||''),credentials:text(b.credentials||'',0,3000),availability:text(b.availability||'',0,2000),featured:b.featured===true};}
 if(kind==='planner'){const trackId=text(b.trackId,1,100);if(!await first(db,"SELECT id FROM records WHERE id=? AND kind='track' AND status<>?",trackId,'archived'))fail(400,'Selecione uma trilha ativa.');if(!Array.isArray(b.items)||b.items.length>100)fail(400,'Configure as tarefas do planner.');const priorities=new Set(['low','normal','high']),currencies=new Set(['EUR','BRL']),items=[];for(const raw of b.items){const cost=raw.estimatedCost===''?'':Number(raw.estimatedCost),dueDays=raw.dueDays===''?'':Number(raw.dueDays);if(cost!==''&&(!Number.isFinite(cost)||cost<0||cost>9999999))fail(400,'Custo estimado inválido.');if(dueDays!==''&&(!Number.isInteger(dueDays)||dueDays<0||dueDays>3650))fail(400,'Prazo estimado inválido.');items.push({id:text(raw.id||uid(),1,100),title:text(raw.title,2,160),phase:text(raw.phase,2,160),description:text(raw.description||'',0,2000),responsibleHint:text(raw.responsibleHint||'',0,120),priority:priorities.has(raw.priority)?raw.priority:'normal',estimatedCost:cost,currency:currencies.has(raw.currency)?raw.currency:'EUR',dueDays,requiredDocuments:text(raw.requiredDocuments||'',0,2000),attachmentRequired:raw.attachmentRequired===true,order:Number.isInteger(Number(raw.order))?Math.max(0,Math.min(10000,Number(raw.order))):items.length});}if(new Set(items.map(i=>i.id)).size!==items.length)fail(400,'Existem tarefas duplicadas.');return{...base,trackId,items:items.sort((a,b)=>a.order-b.order)};}
 if(kind==='event'){const start=Date.parse(b.start),end=Date.parse(b.end);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)fail(400,'Informe início e término válidos.');return{...base,start:new Date(start).toISOString(),end:new Date(end).toISOString(),host:text(b.host||'',0,160),location:text(b.location||'',0,300),joinUrl:urlValue(b.joinUrl||'')};}fail(400,'Tipo de conteúdo inválido.');}

async function api(req,env,path){const db=env.DB;if(!db)fail(503,'O armazenamento está indisponível. Tente novamente.');const method=req.method;
 if(!['GET','HEAD'].includes(method)){if(req.headers.get('Origin')!==new URL(req.url).origin||req.headers.get('X-Arrivo-Request')!=='1')fail(403,'Solicitação não autorizada. Atualize a página.');if(!req.headers.get('content-type')?.startsWith('application/json'))fail(415,'Use dados JSON.');}
 if(path==='/api/auth/status'){const count=await first(db,'SELECT count(*) AS n FROM users');const owner=req.headers.get('oai-authenticated-user-email')?.toLowerCase();return json({setup:count.n===0&&!!env.OWNER_EMAIL&&owner===env.OWNER_EMAIL.toLowerCase()});}
 if(path==='/api/auth/setup'&&method==='POST'){if(!env.OWNER_EMAIL||req.headers.get('oai-authenticated-user-email')?.toLowerCase()!==env.OWNER_EMAIL.toLowerCase())fail(403,'A configuração inicial está disponível somente ao proprietário.');const b=await body(req),name=text(b.name,2,120),pw=password(b.password),mail=env.OWNER_EMAIL.toLowerCase();const u={id:'owner',email:mail,name,password:await bcrypt.hash(pw,12),role:'admin',status:'active',created:now()};const r=await run(db,'INSERT INTO users(id,email,name,password,role,status,created) SELECT ?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM users)',u.id,u.email,u.name,u.password,u.role,u.status,u.created);if(!r.meta.changes)fail(409,'A conta administradora já foi configurada. Entre com sua senha.');await initializeCatalog(db,u);return loginResponse(db,u);}
 if(path==='/api/auth/login'&&method==='POST'){const b=await body(req),mail=email(b.email);await rate(db,'login:'+await hash(mail));await rate(db,'ip:'+await hash(req.headers.get('cf-connecting-ip')||'unknown'),60);const u=await first(db,'SELECT * FROM users WHERE email=?',mail);const pw=typeof b.password==='string'&&b.password.length<=200?b.password:'';const valid=await bcrypt.compare(pw,u?.password||'$2b$12$C6UzMDM.H6dfI/f/IKcEe.5SX2x4lqReGVSjtZKfX9NbTXMC63eEq');if(!u||!valid||u.status!=='active')fail(401,'E-mail ou senha inválidos, ou acesso suspenso.');return loginResponse(db,u);}
 if(path==='/api/auth/activate'&&method==='POST'){const b=await body(req);await rate(db,'activate:'+await hash(req.headers.get('cf-connecting-ip')||'unknown'),30);const t=text(b.token,64,64),name=text(b.name,2,120),pw=password(b.password);const inv=await first(db,'SELECT * FROM invites WHERE token=? AND used=0 AND expires>?',await hash(t),now());if(!inv)fail(400,'Este link expirou ou já foi utilizado. Solicite um novo ao administrador.');const stored=await bcrypt.hash(pw,12);const existing=await first(db,'SELECT * FROM users WHERE email=?',inv.email);if(inv.kind==='reset'&&!existing)fail(400,'Conta não encontrada.');if(inv.kind==='invite'&&existing)fail(409,'Esta conta já existe. Use a recuperação de acesso.');const used=await run(db,'UPDATE invites SET used=1 WHERE token=? AND used=0 AND expires>?',inv.token,now());if(!used.meta.changes)fail(409,'Link já utilizado.');const id=existing?.id||uid();await db.batch([inv.kind==='reset'?stmt(db,'UPDATE users SET password=? WHERE id=?',stored,id):stmt(db,'INSERT INTO users(id,email,name,password,role,status,created) VALUES(?,?,?,?,?,?,?)',id,inv.email,name,stored,inv.role,'active',now()),stmt(db,'DELETE FROM sessions WHERE user_id=?',id)]);return json({ok:true,message:'Senha definida. Entre com seu e-mail.'});}
 const u=await session(req,db);if(!u)fail(401,'Entre na sua conta para continuar.');
 if(path==='/api/auth/me'&&method==='GET')return json({user:cleanUser(u)});
 if(path==='/api/auth/logout'&&method==='POST'){await run(db,'DELETE FROM sessions WHERE token=?',u.session_token);return json({ok:true},200,{'Set-Cookie':`${cookieName}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`});}
 if(path==='/api/profile'&&method==='PUT'){const b=await body(req);await run(db,'UPDATE users SET name=? WHERE id=?',text(b.name,2,120),u.id);return json({ok:true});}
 if(path==='/api/password'&&method==='PUT'){const b=await body(req);await rate(db,'password:'+u.id);if(!await bcrypt.compare(String(b.current||''),u.password))fail(400,'A senha atual está incorreta.');await db.batch([stmt(db,'UPDATE users SET password=? WHERE id=?',await bcrypt.hash(password(b.password),12),u.id),stmt(db,'DELETE FROM sessions WHERE user_id=? AND token<>?',u.id,u.session_token)]);return json({ok:true});}
 if(path==='/api/catalog'&&method==='GET'){const rows=(await all(db,"SELECT * FROM records WHERE kind IN ('track','module','lesson','event','planner','provider') AND status='published'")).map(readRecord);const modules=new Set(rows.filter(r=>r.kind==='module').map(r=>r.id));return json({records:rows.filter(r=>r.kind!=='lesson'||modules.has(r.moduleId)).map(r=>r.kind==='track'?{...r,groups:r.groups.map(g=>[g[0],g[1].filter(id=>modules.has(id))])}:r)});}
 if(path==='/api/learner'&&method==='GET')return json({data:Object.fromEntries((await all(db,'SELECT key,value FROM learner WHERE user_id=?',u.id)).map(r=>[r.key,JSON.parse(r.value)]))});
 if(path==='/api/learner'&&method==='PUT'){const b=await body(req),key=text(b.key,1,150);if(!/^(note|complete|favorite|task|active|history|planner):[a-zA-Z0-9_-]{1,100}$/.test(key))fail(400,'Registro inválido.');let value=key.startsWith('note:')?text(b.value,0,20000):b.value;if(key.startsWith('planner:'))value=await validatePlanner(db,key.split(':')[1],value);else if(typeof value!=='boolean'&&typeof value!=='string'&&typeof value!=='number')fail(400,'Valor inválido.');if(JSON.stringify(value).length>(key.startsWith('planner:')?90000:21000))fail(400,'Conteúdo muito grande.');if(key.startsWith('complete:')||key.startsWith('note:')){const lesson=await first(db,"SELECT * FROM records WHERE id=? AND kind='lesson' AND status='published'",key.split(':')[1]);if(!lesson)fail(400,'Aula indisponível.');const m=JSON.parse(lesson.body).moduleId;if(!await first(db,"SELECT id FROM records WHERE id=? AND status='published'",m))fail(400,'Módulo indisponível.');}await run(db,'INSERT INTO learner(user_id,key,value,updated) VALUES(?,?,?,?) ON CONFLICT(user_id,key) DO UPDATE SET value=excluded.value,updated=excluded.updated',u.id,key,JSON.stringify(value),now());return json({ok:true});}
 if(path==='/api/planner/attachments'&&method==='GET'){const url=new URL(req.url),trackId=text(url.searchParams.get('track')||'',1,100),itemId=url.searchParams.get('item');if(itemId)await plannerTarget(db,trackId,text(itemId,1,100));else if(!await first(db,"SELECT id FROM records WHERE id=? AND kind='track' AND status='published'",trackId))fail(400,'Trilha indisponível.');const rows=await all(db,'SELECT id,track_id AS trackId,item_id AS itemId,name,type,size,created FROM planner_attachments WHERE user_id=? AND track_id=? ORDER BY created DESC',u.id,trackId);return json({attachments:rows});}
 if(path==='/api/planner/attachments'&&method==='POST'){const b=await body(req),trackId=text(b.trackId,1,100),itemId=text(b.itemId,1,100);await plannerTarget(db,trackId,itemId);const count=await first(db,'SELECT count(*) AS n FROM planner_attachments WHERE user_id=? AND track_id=? AND item_id=?',u.id,trackId,itemId);if(count.n>=5)fail(400,'Cada etapa aceita até cinco anexos.');const file=attachmentData(b.data),id=uid(),name=text(b.name,1,160);await run(db,'INSERT INTO planner_attachments(id,user_id,track_id,item_id,name,type,size,data,created) VALUES(?,?,?,?,?,?,?,?,?)',id,u.id,trackId,itemId,name,file.type,file.size,file.data,now());return json({attachment:{id,trackId,itemId,name,type:file.type,size:file.size,created:now()}});}
 if(path.startsWith('/api/planner/attachments/')&&method==='GET'){const id=path.split('/').pop(),row=await first(db,'SELECT * FROM planner_attachments WHERE id=? AND user_id=?',id,u.id);if(!row)fail(404,'Anexo não encontrado.');return attachmentResponse(row,new URL(req.url).searchParams.get('download')==='1');}
 if(path.startsWith('/api/planner/attachments/')&&method==='DELETE'){const id=path.split('/').pop(),result=await run(db,'DELETE FROM planner_attachments WHERE id=? AND user_id=?',id,u.id);if(!result.meta.changes)fail(404,'Anexo não encontrado.');return json({ok:true});}
 if(path==='/api/bookings'&&method==='GET'){const rows=await all(db,"SELECT bookings.*,records.body AS provider_body FROM bookings JOIN records ON records.id=bookings.provider_id WHERE bookings.user_id=? ORDER BY bookings.start DESC",u.id);return json({bookings:rows.map(r=>({...r,provider:JSON.parse(r.provider_body).title,provider_body:undefined}))});}
 if(path==='/api/bookings'&&method==='POST'){const b=await body(req),providerId=text(b.providerId,1,100),provider=await first(db,"SELECT * FROM records WHERE id=? AND kind='provider' AND status='published'",providerId);if(!provider)fail(400,'Prestador indisponível.');const start=Date.parse(b.start);if(!Number.isFinite(start)||start<Date.now()+3600000||start>Date.now()+31536000000)fail(400,'Escolha um horário futuro válido.');const details=JSON.parse(provider.body),conflict=await first(db,"SELECT id FROM bookings WHERE provider_id=? AND start=? AND status IN ('requested','confirmed')",providerId,new Date(start).toISOString());if(conflict)fail(409,'Este horário acabou de ser solicitado. Escolha outro.');const id=uid(),responseToken=token();await run(db,'INSERT INTO bookings(id,user_id,provider_id,start,duration,price,currency,status,payment_status,message,response_token,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',id,u.id,providerId,new Date(start).toISOString(),details.duration,details.price,details.currency,'requested','pending',text(b.message||'',0,2000),await hash(responseToken),now(),now());return json({booking:{id,status:'requested'},providerResponseLink:new URL(req.url).origin+'/#fornitore-resposta?token='+responseToken});}
 if(path==='/api/questions'&&method==='GET'){const rows=await all(db,"SELECT * FROM records WHERE kind='question'");return json({questions:rows.map(readRecord).filter(r=>r.studentId===u.id)});}
 if(path==='/api/questions'&&method==='POST'){const b=await body(req),lessonId=text(b.lessonId,1,100);if(!await first(db,"SELECT id FROM records WHERE id=? AND kind='lesson' AND status='published'",lessonId))fail(400,'Aula indisponível.');await rate(db,'question:'+u.id,30);const id=uid();await run(db,'INSERT INTO records(id,kind,body,status,revision,updated) VALUES(?,?,?,?,1,?)',id,'question',JSON.stringify({studentId:u.id,studentName:u.name,lessonId,text:text(b.text,3,4000),answer:''}),'open',now());return json({ok:true});}
 if(!path.startsWith('/api/admin/'))fail(404,'Página não encontrada.');if(u.role!=='admin')fail(403,'Este recurso é exclusivo da administração.');
 if(path==='/api/admin/bookings'&&method==='GET'){const rows=await all(db,"SELECT bookings.*,users.name AS studentName,users.email AS studentEmail,records.body AS provider_body FROM bookings JOIN users ON users.id=bookings.user_id JOIN records ON records.id=bookings.provider_id ORDER BY bookings.created DESC");return json({bookings:rows.map(r=>({...r,provider:JSON.parse(r.provider_body).title,providerEmail:JSON.parse(r.provider_body).email,provider_body:undefined}))});}
 if(path.startsWith('/api/admin/bookings/')&&method==='PUT'){const id=path.split('/').pop(),b=await body(req),status=['requested','confirmed','declined','cancelled'].includes(b.status)?b.status:null,payment=['pending','paid','refunded','waived'].includes(b.paymentStatus)?b.paymentStatus:null;if(!status||!payment)fail(400,'Situação inválida.');const result=await run(db,'UPDATE bookings SET status=?,payment_status=?,meeting_url=?,updated=? WHERE id=?',status,payment,urlValue(b.meetingUrl||''),now(),id);if(!result.meta.changes)fail(404,'Agendamento não encontrado.');return json({ok:true});}
 if(path==='/api/admin/records'&&method==='GET')return json({records:(await all(db,'SELECT * FROM records ORDER BY updated DESC')).map(readRecord)});
 if(path==='/api/admin/records'&&method==='POST'){const b=await body(req),kind=text(b.kind,1,20),id=uid(),status=['draft','published'].includes(b.status)?b.status:'draft';if(kind==='planner'&&await first(db,"SELECT id FROM records WHERE kind='planner' AND json_extract(body,'$.trackId')=?",b.trackId))fail(409,'Esta trilha já possui um modelo de planner.');const record=await validateRecord(db,kind,b,status,id);await db.batch([stmt(db,'INSERT INTO records(id,kind,body,status,revision,updated) VALUES(?,?,?,?,1,?)',id,kind,JSON.stringify(record),status,now()),audit(db,u,'create',id)]);return json({id});}
 if(path.startsWith('/api/admin/records/')&&method==='PUT'){const id=path.split('/').pop(),b=await body(req),old=await first(db,'SELECT * FROM records WHERE id=?',id);if(!old)fail(404,'Conteúdo não encontrado.');if(old.kind==='question'){const content={...JSON.parse(old.body),answer:text(b.answer,1,6000)};const r=await run(db,'UPDATE records SET body=?,status=?,revision=revision+1,updated=? WHERE id=? AND revision=?',JSON.stringify(content),'answered',now(),id,b.revision);if(!r.meta.changes)fail(409,'O registro foi alterado. Atualize a página.');return json({ok:true});}if(!['draft','published','archived'].includes(b.status))fail(400,'Estado inválido.');const content=await validateRecord(db,old.kind,b,b.status,id);const r=await run(db,'UPDATE records SET body=?,status=?,revision=revision+1,updated=? WHERE id=? AND revision=?',JSON.stringify(content),b.status,now(),id,b.revision);if(!r.meta.changes)fail(409,'Outra edição foi salva. Reabra o registro antes de tentar novamente.');await audit(db,u,'update:'+b.status,id).run();return json({ok:true});}
 if(path==='/api/admin/users'&&method==='GET'){const users=(await all(db,'SELECT id,email,name,role,status,created FROM users ORDER BY created DESC')).map(cleanUser);return json({users,invites:await all(db,'SELECT email,role,kind,expires,used FROM invites WHERE expires>? ORDER BY expires DESC',now())});}
 if(path.startsWith('/api/admin/users/')&&method==='PUT'){const id=path.split('/').pop(),b=await body(req);if(id===u.id||id==='owner')fail(400,'A conta proprietária e sua própria permissão não podem ser alteradas aqui.');if(!['admin','student'].includes(b.role)||!['active','suspended'].includes(b.status))fail(400,'Perfil inválido.');if(!await first(db,'SELECT id FROM users WHERE id=?',id))fail(404,'Conta não encontrada.');await db.batch([stmt(db,'UPDATE users SET role=?,status=? WHERE id=?',b.role,b.status,id),stmt(db,'DELETE FROM sessions WHERE user_id=?',id),audit(db,u,'user:'+b.role+':'+b.status,id)]);return json({ok:true});}
 if(path==='/api/admin/invites'&&method==='POST'){const b=await body(req),mail=email(b.email),kind=b.kind==='reset'?'reset':'invite',role=b.role==='admin'?'admin':'student';const existing=await first(db,'SELECT * FROM users WHERE email=?',mail);if(kind==='invite'&&existing)fail(409,'Este e-mail já tem uma conta.');if(kind==='reset'&&!existing)fail(404,'Conta não encontrada.');const raw=token(),expires=now()+86400;await db.batch([stmt(db,'UPDATE invites SET used=1 WHERE email=?',mail),stmt(db,'INSERT INTO invites(token,email,role,kind,expires,used) VALUES(?,?,?,?,?,0)',await hash(raw),mail,existing?.role||role,kind,expires),audit(db,u,kind,mail)]);return json({token:raw,expires,email:mail});}
 if(path==='/api/admin/audit'&&method==='GET')return json({entries:await all(db,'SELECT audit.*,users.name AS actorName FROM audit LEFT JOIN users ON users.id=audit.actor ORDER BY audit.created DESC LIMIT 100')});
 fail(404,'Recurso não encontrado.');
}
export default{async fetch(req,env){const path=new URL(req.url).pathname;try{if(path.startsWith('/api/'))return await api(req,env,path);if(!['GET','HEAD'].includes(req.method))return new Response('Method not allowed',{status:405});const asset=assets[path==='/'?'/index.html':path];if(!asset)return new Response('Not found',{status:404});return new Response(req.method==='HEAD'?null:asset.body,{headers:{'Content-Type':asset.type,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data: https:; frame-src https://www.youtube-nocookie.com https://player.vimeo.com; media-src https:; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com"}});}catch(e){if(!e.status)console.error('Request failed',path,e.message);return json({error:e.status?e.message:'Não foi possível concluir. Seus dados permanecem no formulário; tente novamente.'},e.status||503);}}};
