import {sqliteTable,text,integer,real,primaryKey,index} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),password:text('password'),role:text('role').notNull().default('student'),status:text('status').notNull().default('active'),created:integer('created').notNull()});
export const sessions=sqliteTable('sessions',{token:text('token').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expires:integer('expires').notNull()},t=>[index('sessions_user').on(t.userId)]);
export const invites=sqliteTable('invites',{token:text('token').primaryKey(),email:text('email').notNull(),role:text('role').notNull().default('student'),kind:text('kind').notNull(),expires:integer('expires').notNull(),used:integer('used').notNull().default(0)},t=>[index('invites_email').on(t.email)]);
export const records=sqliteTable('records',{id:text('id').primaryKey(),kind:text('kind').notNull(),body:text('body').notNull(),status:text('status').notNull(),revision:integer('revision').notNull().default(1),updated:integer('updated').notNull()},t=>[index('records_kind_status').on(t.kind,t.status)]);
export const learner=sqliteTable('learner',{userId:text('user_id').notNull().references(()=>users.id),key:text('key').notNull(),value:text('value').notNull(),updated:integer('updated').notNull()},t=>[primaryKey({columns:[t.userId,t.key]})]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),created:integer('created').notNull()},t=>[index('audit_created').on(t.created)]);
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),count:integer('count').notNull(),until:integer('until').notNull()});

export const plannerAttachments=sqliteTable('planner_attachments',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),trackId:text('track_id').notNull(),itemId:text('item_id').notNull(),name:text('name').notNull(),type:text('type').notNull(),size:integer('size').notNull(),data:text('data').notNull(),created:integer('created').notNull()},t=>[index('planner_attachments_owner').on(t.userId,t.trackId,t.itemId)]);

export const bookings=sqliteTable('bookings',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),providerId:text('provider_id').notNull().references(()=>records.id),start:text('start').notNull(),duration:integer('duration').notNull(),price:real('price').notNull(),currency:text('currency').notNull(),status:text('status').notNull(),paymentStatus:text('payment_status').notNull(),message:text('message').notNull(),meetingUrl:text('meeting_url'),responseToken:text('response_token').notNull(),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('bookings_user').on(t.userId,t.start),index('bookings_provider').on(t.providerId,t.start)]);
